export const DRILLING_UNITS = [
  {
    key: '3_gas',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(140, 49, 57)',
  },
  {
    key: '3gas',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(140, 49, 57)',
  },
  {
    key: 'ADTSP',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(41, 61, 246)',
  },
  {
    key: 'Ann Press Dh',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(44, 196, 124)',
  },
  {
    key: 'Annular Back Pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(80, 112, 224)',
  },
  {
    key: 'Annular Pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(80, 112, 224)',
  },
  {
    key: 'Back Pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(80, 112, 224)',
  },
  {
    key: 'DDPSP',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(93, 81, 166)',
  },
  {
    key: 'Ecd Bit',
    unitType: 'density',
    unit: 'ppg',
    color: 'rgb(78, 13, 184)',
  },
  {
    key: 'MDEN',
    unitType: 'density',
    unit: 'ppg',
    color: 'rgb(21, 120, 164)',
  },
  {
    key: 'TDSTA',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(145, 173, 207)',
  },
  {
    key: 'Top Drive State',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(145, 173, 207)',
  },
  {
    key: 'active',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(222, 48, 136)',
  },
  {
    key: 'active_pit_volume',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(222, 48, 136)',
  },
  {
    key: 'ad delta p set point',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(93, 81, 166)',
  },
  {
    key: 'ad delta p setpoint',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(93, 81, 166)',
  },
  {
    key: 'ad rop set point',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(252, 47, 13)',
  },
  {
    key: 'ad rop setpoint',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(252, 47, 13)',
  },
  {
    key: 'ad wob set point',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(149, 193, 70)',
  },
  {
    key: 'ad wob setpoint',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(149, 193, 70)',
  },
  {
    key: 'ad_diff_press_setpoint',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(93, 81, 166)',
  },
  {
    key: 'ad_rop_setpoint',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(252, 47, 13)',
  },
  {
    key: 'ad_torque_limit',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(41, 61, 246)',
  },
  {
    key: 'ad_wob_setpoint',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(149, 193, 70)',
  },
  {
    key: 'addiffpresspval',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(93, 81, 166)',
  },
  {
    key: 'adropactual',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(252, 47, 13)',
  },
  {
    key: 'adtsp',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(41, 61, 246)',
  },
  {
    key: 'adwoblimit',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(149, 193, 70)',
  },
  {
    key: 'ann_press_dh',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(44, 196, 124)',
  },
  {
    key: 'annular_back_pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(80, 112, 224)',
  },
  {
    key: 'annulus_pressure_loss',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(42, 67, 105)',
  },
  {
    key: 'autodriller diff press sp',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(93, 81, 166)',
  },
  {
    key: 'autodriller on bottom rop setpoint',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(252, 47, 13)',
  },
  {
    key: 'autodriller wob sp',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(149, 193, 70)',
  },
  {
    key: 'axial_shock',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(55, 227, 164)',
  },
  {
    key: 'bdep',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(177, 176, 193)',
  },
  {
    key: 'bht',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(130, 249, 65)',
  },
  {
    key: 'bit depth',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(177, 176, 193)',
  },
  {
    key: 'bit position',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(177, 176, 193)',
  },
  {
    key: 'bit weight',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(29, 178, 240)',
  },
  {
    key: 'bit_depth',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(177, 176, 193)',
  },
  {
    key: 'bit_depth',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(177, 176, 193)',
  },
  {
    key: 'bitdepth',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(177, 176, 193)',
  },
  {
    key: 'blkpos',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(130, 249, 65)',
  },
  {
    key: 'block height',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(130, 249, 65)',
  },
  {
    key: 'block_height',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(130, 249, 65)',
  },
  {
    key: 'block_pos',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(130, 249, 65)',
  },
  {
    key: 'bpos',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(130, 249, 65)',
  },
  {
    key: 'casing_pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(244, 83, 6)',
  },
  {
    key: 'choke_pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(42, 128, 112)',
  },
  {
    key: 'continuous_inclination',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(250, 163, 121)',
  },
  {
    key: 'cp',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(42, 128, 112)',
  },
  {
    key: 'dacon',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(120, 11, 4)',
  },
  {
    key: 'dadoc',
    unitType: 'lengthPerAngle',
    unit: 'in/rev',
    color: 'rgb(50, 220, 26)',
  },
  {
    key: 'dals',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(39, 230, 192)',
  },
  {
    key: 'damse',
    unitType: 'msePressure',
    unit: 'ksi',
    color: 'rgb(134, 106, 208)',
  },
  {
    key: 'damu',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(238, 40, 243)',
  },
  {
    key: 'darf',
    unitType: 'volumeFlowRate',
    unit: 'gal/min',
    color: 'rgb(15, 13, 187)',
  },
  {
    key: 'darop',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(205, 228, 171)',
  },
  {
    key: 'darr',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(176, 234, 119)',
  },
  {
    key: 'darw',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(212, 222, 105)',
  },
  {
    key: 'das_bha_tse',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(106, 235, 91)',
  },
  {
    key: 'das_bit_rpm_max',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(125, 47, 112)',
  },
  {
    key: 'das_bit_rpm_min',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(169, 238, 56)',
  },
  {
    key: 'das_doc',
    unitType: 'lengthPerAngle',
    unit: 'in/rev',
    color: 'rgb(50, 220, 26)',
  },
  {
    key: 'das_downhole_mse',
    unitType: 'msePressure',
    unit: 'ksi',
    color: 'rgb(28, 78, 201)',
  },
  {
    key: 'das_in_control',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(120, 11, 4)',
  },
  {
    key: 'das_learning_score',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(39, 230, 192)',
  },
  {
    key: 'das_mse',
    unitType: 'msePressure',
    unit: 'ksi',
    color: 'rgb(134, 106, 208)',
  },
  {
    key: 'das_mu',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(238, 40, 243)',
  },
  {
    key: 'das_recommended_flow',
    unitType: 'volumeFlowRate',
    unit: 'gal/min',
    color: 'rgb(15, 13, 187)',
  },
  {
    key: 'das_recommended_rop',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(208, 168, 119)',
  },
  {
    key: 'das_recommended_rpm',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(176, 234, 119)',
  },
  {
    key: 'das_recommended_wob',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(212, 222, 105)',
  },
  {
    key: 'das_rop',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(205, 228, 171)',
  },
  {
    key: 'das_rop_limiting_max',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(159, 209, 121)',
  },
  {
    key: 'das_rop_lower_limit',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(76, 232, 70)',
  },
  {
    key: 'das_rop_upper_limit',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(198, 193, 177)',
  },
  {
    key: 'das_rpm_lower_limit',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(214, 48, 4)',
  },
  {
    key: 'das_rpm_upper_limit',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(191, 120, 75)',
  },
  {
    key: 'das_stall_detector_status',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(80, 52, 176)',
  },
  {
    key: 'das_status',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(3, 8, 63)',
  },
  {
    key: 'das_stick_slip',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(230, 1, 46)',
  },
  {
    key: 'das_time',
    unitType: 'time',
    unit: 's',
    color: 'rgb(249, 117, 130)',
  },
  {
    key: 'das_wob_lower_limit',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(119, 47, 2)',
  },
  {
    key: 'das_wob_upper_limit',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(28, 24, 172)',
  },
  {
    key: 'dasds',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(80, 52, 176)',
  },
  {
    key: 'dasst',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(3, 8, 63)',
  },
  {
    key: 'datm',
    unitType: 'time',
    unit: 's',
    color: 'rgb(249, 117, 130)',
  },
  {
    key: 'datse',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(230, 1, 46)',
  },
  {
    key: 'dbrmn',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(169, 238, 56)',
  },
  {
    key: 'dbrmx',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(125, 47, 112)',
  },
  {
    key: 'dbtse',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(106, 235, 91)',
  },
  {
    key: 'ddpsp',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(93, 81, 166)',
  },
  {
    key: 'dept',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(100, 80, 245)',
  },
  {
    key: 'deptbitm',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(177, 176, 193)',
  },
  {
    key: 'deptmeas',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(100, 80, 245)',
  },
  {
    key: 'diff',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(99, 115, 144)',
  },
  {
    key: 'diff press',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(99, 115, 144)',
  },
  {
    key: 'diff_press',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(99, 115, 144)',
  },
  {
    key: 'diff_press',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(99, 115, 144)',
  },
  {
    key: 'differential pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(99, 115, 144)',
  },
  {
    key: 'diffpres',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(99, 115, 144)',
  },
  {
    key: 'difp',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(99, 115, 144)',
  },
  {
    key: 'dmsed',
    unitType: 'msePressure',
    unit: 'ksi',
    color: 'rgb(28, 78, 201)',
  },
  {
    key: 'downhole_mse',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(29, 89, 29)',
  },
  {
    key: 'drillsmart_onoff',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(69, 118, 76)',
  },
  {
    key: 'drmln',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(214, 48, 4)',
  },
  {
    key: 'drmlx',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(191, 120, 75)',
  },
  {
    key: 'drplm',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(159, 209, 121)',
  },
  {
    key: 'drpln',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(76, 232, 70)',
  },
  {
    key: 'drplx',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(198, 193, 177)',
  },
  {
    key: 'drrop',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(208, 168, 119)',
  },
  {
    key: 'dtdsp',
    unitType: 'speed',
    unit: 'ft/h',
    color: 'rgb(252, 47, 13)',
  },
  {
    key: 'dwbln',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(119, 47, 2)',
  },
  {
    key: 'dwblx',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(28, 24, 172)',
  },
  {
    key: 'dynin',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(250, 163, 121)',
  },
  {
    key: 'ecd_at_bit',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(175, 247, 50)',
  },
  {
    key: 'ecd_bit',
    unitType: 'density',
    unit: 'ppg',
    color: 'rgb(78, 13, 184)',
  },
  {
    key: 'fast_rop_ft_hr',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(7, 129, 197)',
  },
  {
    key: 'flow',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(32, 98, 232)',
  },
  {
    key: 'flow 1 gain/loss',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(2, 11, 211)',
  },
  {
    key: 'flow in rate',
    unitType: 'volumeFlowRate',
    unit: 'gal/min',
    color: 'rgb(225, 174, 184)',
  },
  {
    key: 'flow out %',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(32, 98, 232)',
  },
  {
    key: 'flow out percent',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(32, 98, 232)',
  },
  {
    key: 'flow out rate',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(32, 98, 232)',
  },
  {
    key: 'flow_in',
    unitType: 'volumeFlowRate',
    unit: 'gal/min',
    color: 'rgb(225, 174, 184)',
  },
  {
    key: 'flow_out',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(32, 98, 232)',
  },
  {
    key: 'flow_out_percent',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(32, 98, 232)',
  },
  {
    key: 'flow_out_rel',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(32, 98, 232)',
  },
  {
    key: 'flowin',
    unitType: 'volumeFlowRate',
    unit: 'gal/min',
    color: 'rgb(225, 174, 184)',
  },
  {
    key: 'gain loss',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(2, 11, 211)',
  },
  {
    key: 'gain_loss',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(2, 11, 211)',
  },
  {
    key: 'gainloss',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(2, 11, 211)',
  },
  {
    key: 'gam',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(91, 49, 175)',
  },
  {
    key: 'gamma',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(91, 49, 175)',
  },
  {
    key: 'gamma ray',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(91, 49, 175)',
  },
  {
    key: 'gamma_ray',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(91, 49, 175)',
  },
  {
    key: 'gamma_ray',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(91, 49, 175)',
  },
  {
    key: 'gas_total',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(140, 49, 57)',
  },
  {
    key: 'gr',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(91, 49, 175)',
  },
  {
    key: 'gravity tool face',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(147, 203, 22)',
  },
  {
    key: 'gravity toolface',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(147, 203, 22)',
  },
  {
    key: 'gravity_tool_face',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(147, 203, 22)',
  },
  {
    key: 'gravity_tool_face',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(147, 203, 22)',
  },
  {
    key: 'grc',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(91, 49, 175)',
  },
  {
    key: 'gtf',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(147, 203, 22)',
  },
  {
    key: 'hkla',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(7, 192, 63)',
  },
  {
    key: 'hl',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(7, 192, 63)',
  },
  {
    key: 'hole depth',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(100, 80, 245)',
  },
  {
    key: 'hole_depth',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(100, 80, 245)',
  },
  {
    key: 'holedepth',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(100, 80, 245)',
  },
  {
    key: 'hook load',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(7, 192, 63)',
  },
  {
    key: 'hook_load',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(7, 192, 63)',
  },
  {
    key: 'hookload',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(7, 192, 63)',
  },
  {
    key: 'hookload_max',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(7, 192, 63)',
  },
  {
    key: 'kill_pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(219, 41, 198)',
  },
  {
    key: 'kp',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(219, 41, 198)',
  },
  {
    key: 'lateral_shock',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(163, 235, 149)',
  },
  {
    key: 'magnetic tool face',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(223, 252, 240)',
  },
  {
    key: 'magnetic toolface',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(223, 252, 240)',
  },
  {
    key: 'magnetic_tool_face',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(223, 252, 240)',
  },
  {
    key: 'magnetic_tool_face',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(223, 252, 240)',
  },
  {
    key: 'mfia',
    unitType: 'volumeFlowRate',
    unit: 'gal/min',
    color: 'rgb(225, 174, 184)',
  },
  {
    key: 'mfop',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(32, 98, 232)',
  },
  {
    key: 'mp1_spm',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(6, 88, 126)',
  },
  {
    key: 'mp1_stk',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(3, 243, 161)',
  },
  {
    key: 'mp2_spm',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(118, 231, 113)',
  },
  {
    key: 'mp2_stk',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(68, 240, 120)',
  },
  {
    key: 'mp3_spm',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(247, 22, 178)',
  },
  {
    key: 'mp3_stk',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(134, 249, 253)',
  },
  {
    key: 'mp4_spm',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(217, 116, 6)',
  },
  {
    key: 'mtf',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(223, 252, 240)',
  },
  {
    key: 'mud_density',
    unitType: 'density',
    unit: 'ppg',
    color: 'rgb(21, 120, 164)',
  },
  {
    key: 'mud_flow_in',
    unitType: 'volumeFlowRate',
    unit: 'gal/min',
    color: 'rgb(225, 174, 184)',
  },
  {
    key: 'mud_flow_out',
    unitType: 'volumeFlowRate',
    unit: 'gal/min',
    color: 'rgb(188, 11, 94)',
  },
  {
    key: 'mud_flow_out_percent',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(32, 98, 232)',
  },
  {
    key: 'mwd_annulus_ecd',
    unitType: 'density',
    unit: 'ppg',
    color: 'rgb(78, 13, 184)',
  },
  {
    key: 'mwd_annulus_pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(44, 196, 124)',
  },
  {
    key: 'mwd_downhole_stick_slip',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(55, 19, 39)',
  },
  {
    key: 'obr',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(7, 129, 197)',
  },
  {
    key: 'on bottom rop',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(7, 129, 197)',
  },
  {
    key: 'pcas',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(244, 83, 6)',
  },
  {
    key: 'pdm_rpm',
    unitType: null,
    unit: 'rpm',
    color: 'rgb(30, 189, 113)',
  },
  {
    key: 'pdm_torque',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(153, 150, 137)',
  },
  {
    key: 'pgas',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(140, 49, 57)',
  },
  {
    key: 'pit_volume_1',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(3, 119, 26)',
  },
  {
    key: 'pit_volume_2',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(189, 133, 33)',
  },
  {
    key: 'pit_volume_3',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(222, 252, 49)',
  },
  {
    key: 'pit_volume_4',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(215, 185, 204)',
  },
  {
    key: 'pit_volume_5',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(91, 207, 60)',
  },
  {
    key: 'pit_volume_6',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(74, 52, 130)',
  },
  {
    key: 'pit_volume_7',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(85, 89, 47)',
  },
  {
    key: 'predicted_ecd_at_casing',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(71, 16, 41)',
  },
  {
    key: 'process_auto_onoff',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(210, 98, 43)',
  },
  {
    key: 'pump 1 strokes/min',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(6, 88, 126)',
  },
  {
    key: 'pump 1 strokes/min',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(3, 243, 161)',
  },
  {
    key: 'pump 1 total strokes',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(3, 243, 161)',
  },
  {
    key: 'pump 2 strokes/min',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(118, 231, 113)',
  },
  {
    key: 'pump 2 strokes/min',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(68, 240, 120)',
  },
  {
    key: 'pump 2 total strokes',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(68, 240, 120)',
  },
  {
    key: 'pump 3 strokes/min',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(247, 22, 178)',
  },
  {
    key: 'pump 3 strokes/min',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(134, 249, 253)',
  },
  {
    key: 'pump 3 total strokes',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(134, 249, 253)',
  },
  {
    key: 'pump 4 strokes/min',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(217, 116, 6)',
  },
  {
    key: 'pump pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(240, 179, 223)',
  },
  {
    key: 'pump spm - total',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(200, 43, 208)',
  },
  {
    key: 'pump spm 1',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(6, 88, 126)',
  },
  {
    key: 'pump spm 2',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(118, 231, 113)',
  },
  {
    key: 'pump spm 3',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(247, 22, 178)',
  },
  {
    key: 'pump spm 4',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(217, 116, 6)',
  },
  {
    key: 'pump total strokes rate',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(200, 43, 208)',
  },
  {
    key: 'pump_displacement',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(200, 43, 208)',
  },
  {
    key: 'pump_spm_1',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(6, 88, 126)',
  },
  {
    key: 'pump_spm_2',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(118, 231, 113)',
  },
  {
    key: 'pump_spm_3',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(247, 22, 178)',
  },
  {
    key: 'pump_spm_4',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(217, 116, 6)',
  },
  {
    key: 'pump_spm_total',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(200, 43, 208)',
  },
  {
    key: 'pump_strokes',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(209, 186, 120)',
  },
  {
    key: 'rate of penetration',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(7, 129, 197)',
  },
  {
    key: 'recommended_minimum_flowrate',
    unitType: 'volume',
    unit: 'gal',
    color: 'rgb(202, 166, 57)',
  },
  {
    key: 'revit_onoff',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(53, 14, 33)',
  },
  {
    key: 'rocker_status',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(145, 173, 207)',
  },
  {
    key: 'rockit_onoff',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(158, 172, 11)',
  },
  {
    key: 'rockit_pilot_onoff',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(19, 95, 242)',
  },
  {
    key: 'rop',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(7, 129, 197)',
  },
  {
    key: 'rop',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(7, 129, 197)',
  },
  {
    key: 'rop - average',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(7, 129, 197)',
  },
  {
    key: 'rop_average',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(195, 57, 16)',
  },
  {
    key: 'ropa',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(7, 129, 197)',
  },
  {
    key: 'rotary rpm',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(97, 82, 181)',
  },
  {
    key: 'rotary torque',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(147, 196, 93)',
  },
  {
    key: 'rotary_rpm',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(97, 82, 181)',
  },
  {
    key: 'rotary_torque',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(147, 196, 93)',
  },
  {
    key: 'rpm',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(97, 82, 181)',
  },
  {
    key: 'rpmtd',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(97, 82, 181)',
  },
  {
    key: 'spm1',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(6, 88, 126)',
  },
  {
    key: 'spm2',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(118, 231, 113)',
  },
  {
    key: 'spm3',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(247, 22, 178)',
  },
  {
    key: 'spm4',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(217, 116, 6)',
  },
  {
    key: 'spmtot',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(200, 43, 208)',
  },
  {
    key: 'spp',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(240, 179, 223)',
  },
  {
    key: 'sppa',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(240, 179, 223)',
  },
  {
    key: 'srv_gra_tf',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(147, 203, 22)',
  },
  {
    key: 'srv_mag_tf',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(223, 252, 240)',
  },
  {
    key: 'standpipe pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(240, 179, 223)',
  },
  {
    key: 'standpipe_pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(240, 179, 223)',
  },
  {
    key: 'stp_prs_1',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(240, 179, 223)',
  },
  {
    key: 'strks_pump_1',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(3, 243, 161)',
  },
  {
    key: 'strks_pump_2',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(68, 240, 120)',
  },
  {
    key: 'strks_pump_3',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(134, 249, 253)',
  },
  {
    key: 'strks_total',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(209, 186, 120)',
  },
  {
    key: 'surface_torque',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(237, 92, 19)',
  },
  {
    key: 'svygtf',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(147, 203, 22)',
  },
  {
    key: 'svymtf',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(223, 252, 240)',
  },
  {
    key: 'td_speed',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(97, 82, 181)',
  },
  {
    key: 'td_torque',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(147, 196, 93)',
  },
  {
    key: 'toolface grav',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(147, 203, 22)',
  },
  {
    key: 'toolface mag',
    unitType: 'angle',
    unit: 'deg',
    color: 'rgb(223, 252, 240)',
  },
  {
    key: 'top drive rpm',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(97, 82, 181)',
  },
  {
    key: 'top drive torque',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(147, 196, 93)',
  },
  {
    key: 'tor',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(147, 196, 93)',
  },
  {
    key: 'torqtdfl',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(147, 196, 93)',
  },
  {
    key: 'torque',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(147, 196, 93)',
  },
  {
    key: 'tot_dpt_md',
    unitType: 'length',
    unit: 'ft',
    color: 'rgb(100, 80, 245)',
  },
  {
    key: 'tot_spm',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(200, 43, 208)',
  },
  {
    key: 'total pump output',
    unitType: 'volumeFlowRate',
    unit: 'gal/min',
    color: 'rgb(225, 174, 184)',
  },
  {
    key: 'total strokes p1+p2+p3+p4',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(209, 186, 120)',
  },
  {
    key: 'total_bit_rpm',
    unitType: null,
    unit: 'rpm',
    color: 'rgb(4, 18, 147)',
  },
  {
    key: 'total_bit_torque',
    unitType: 'torque',
    unit: 'ft-lbf',
    color: 'rgb(198, 189, 233)',
  },
  {
    key: 'total_gas',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(140, 49, 57)',
  },
  {
    key: 'total_gas',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(140, 49, 57)',
  },
  {
    key: 'total_pit_volume',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(145, 138, 107)',
  },
  {
    key: 'totalpumpdisplacement',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(200, 43, 208)',
  },
  {
    key: 'tpd',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(200, 43, 208)',
  },
  {
    key: 'tpo',
    unitType: 'volumeFlowRate',
    unit: 'gal/min',
    color: 'rgb(225, 174, 184)',
  },
  {
    key: 'trip_tank_volume_1',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(63, 196, 87)',
  },
  {
    key: 'trip_tank_volume_2',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(161, 230, 82)',
  },
  {
    key: 'trip_tank_volume_3',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(186, 187, 218)',
  },
  {
    key: 'ts1-4',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(209, 186, 120)',
  },
  {
    key: 'ts3',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(134, 249, 253)',
  },
  {
    key: 'ttk1',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(63, 196, 87)',
  },
  {
    key: 'ttk2',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(161, 230, 82)',
  },
  {
    key: 'ttk3',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(186, 187, 218)',
  },
  {
    key: 'vtgl',
    unitType: 'oil',
    unit: 'bbl',
    color: 'rgb(2, 11, 211)',
  },
  {
    key: 'waagg',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(74, 205, 250)',
  },
  {
    key: 'wave_aggressiveness',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(74, 205, 250)',
  },
  {
    key: 'wave_limiting_status',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(128, 218, 127)',
  },
  {
    key: 'wave_sp_tracking_status',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(197, 186, 118)',
  },
  {
    key: 'wave_stick_slip_threshold',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(4, 46, 43)',
  },
  {
    key: 'weight on bit',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(29, 178, 240)',
  },
  {
    key: 'weight on bit',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(29, 178, 240)',
  },
  {
    key: 'weight_on_bit',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(29, 178, 240)',
  },
  {
    key: 'wellhead_pressure',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(110, 4, 38)',
  },
  {
    key: 'whp',
    unitType: 'pressure',
    unit: 'psi',
    color: 'rgb(110, 4, 38)',
  },
  {
    key: 'wls',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(128, 218, 127)',
  },
  {
    key: 'wob',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(29, 178, 240)',
  },
  {
    key: 'woba',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(29, 178, 240)',
  },
  {
    key: 'wobsp',
    unitType: 'force',
    unit: 'klbf',
    color: 'rgb(149, 193, 70)',
  },
  {
    key: 'wsst',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(4, 46, 43)',
  },
  {
    key: 'wsts',
    unitType: 'unitless',
    unit: 'unitless',
    color: 'rgb(197, 186, 118)',
  },
];
