import WarningIcon from '@material-ui/icons/Warning';
import DoneIcon from '@material-ui/icons/Done';
import ErrorIcon from '@material-ui/icons/Error';
import CheckCircleIcon from '@material-ui/icons/CheckCircle';
import { DangerousIcon } from '~/components/Icons/DangerousIcon';

export const MAX_MOBILE_WIDTH = 959;

export type BadgeIconStatus = 'warning' | 'issue' | 'error' | 'success';

export const ALERT_STATUSES = {
  FLAGGED: 'flagged',
  EXPIRED: 'expired',
  RESOLVED: 'resolved',
  OPEN: 'open',
  INVESTIGATION: 'investigation',
  ON_HOLD: 'on hold',
};

export const ALERT_ICONS = {
  Missing: DangerousIcon,
  Issue: ErrorIcon,
  Resolved: CheckCircleIcon,
};

type Issue = 'Issue';
type Missing = 'Missing';

export type AlertState = Issue | Missing;

export const ALERT_STATES: { issue: Issue; missing: Missing } = {
  missing: 'Missing',
  issue: 'Issue',
};

export type Alert = {
  id: string;
  assetId: number;
  deductsFromScore?: number;
  name: string;
  category: string;
  state: AlertState;
  status: string;
  isThrottled: boolean;
  message: string;
  note: string;
  statusUpdatedAt: number;
  lastCheckedAt: number;
  emptyMessage?: string;
};

export type AssetItem = {
  name: string;
  id: number;
  issuesNum: number;
  missingNum: number;
  isResolved?: boolean;
  linkToDQPage: string;
  alert: Alert;
};

export type AssetData = Record<string, AssetItem[]>;

type BadgeIconStatuses = {
  success: 'success';
  warning: 'warning';
  issue: 'issue';
  error: 'error';
};

export const BADGE_ICON_STATUSES: BadgeIconStatuses = {
  success: 'success',
  warning: 'warning',
  issue: 'issue',
  error: 'error',
};

export const BADGE_ICONS = {
  [BADGE_ICON_STATUSES.success]: DoneIcon,
  [BADGE_ICON_STATUSES.warning]: WarningIcon,
  [BADGE_ICON_STATUSES.issue]: ErrorIcon,
  [BADGE_ICON_STATUSES.error]: DangerousIcon,
};

export const WARNING = 'Recommendations may be incorrect based on data quality errors';

export const METADATA = {
  recordProvider: 'corva',
  recordCollections: {
    wellnessAlerts: 'wellness_alerts',
    wcuRuleMapping: 'wcu_rule_mapping',
    wellnessRuleSettings: 'wellness_rule_settings',
    wcuRulesCheckTime: 'wcu-rule-check-time',
  },
};

export const DATA_QUALITY_CHECK_PASSED = 'Data quality check passed';

const DIRECTIONAL_DIVERGENCE_APP_ID_QA = 188;
const TVS_VS_MD_APP_ID_QA = 190;
const RIG_OPERATIONS_APP_ID_QA = 216;
const ASSET_STATUS_APP_ID_QA = 237;
const NPT_EVENTS_APP_ID_QA = 348;
const STAGE_DESIGN_V_ACTUAL_APP_ID_QA = 358;
const PRESSURE_RATE_COMPARISON_APP_ID_QA = 359;
const WELL_COMPARISON_APP_ID_QA = 360;
const ACTIVITY_DETECTION_APP_ID_QA = 361;
const TIME_ANALYSIS_APP_ID_QA = 370;
const TRIPPING_SPEEDS_APP_ID_QA = 375;
const WIRELINE_TRACES_APP_ID_QA = 382;
const SWAP_OVER_TIMES_APP_ID_QA = 389;
const FLUSH_APP_ID_QA = 391;
const DRILLOUT_PARAMETER_SHEET_APP_ID_QA = 392;
const PAD_METRICS_APP_ID_QA = 397;
const KPI_VISUALIZER_APP_ID_QA = 406;
const DRILLOUT_TRACES_APP_ID_QA = 418;

// Drilling Prod Apps:
const DRILLING_ASSET_STATUS_APP_ID_PROD = 84;
const DRILLING_RIG_OPERATIONS_APP_ID_PROD = 32;
const DRILLING_KPI_VISUALIZER_APP_ID_PROD = 196;
const DRILLING_ROP_HEATMAP_APP_ID_PROD = 34;
const DRILLING_LEADERBOARD_APP_ID_PROD = 224;
const DRILLING_TRIPPING_SPEEDS_APP_ID_PROD = 139;
const DRILLING_TRACES_APP_ID_PROD = 80;
const DRILLING_TOOLFACE_VS_MEASURED_DEPTH_APP_ID_PROD = 104;
const DRILLING_BUCKLING_LOAD_ANALYSIS_APP_ID_PROD = 24;
const DRILLING_BHA_OPTIMIZATION_APP_ID_PROD = 131;
const DRILLING_DIRECTIONAL_DIVERGENCE_APP_ID_PROD = 40;
const DRILLING_CIRCULATING_PRESSURE_TREND_APP_ID_PROD = 63;
const DRILLING_ROTARY_TREND_ANALYSIS_APP_ID_PROD = 124;
const DRILLING_SURGE_AND_SWAB_APP_ID_PROD = 121;
const DRILLING_BUCKLING_LOAD_APP_ID_PROD = 24;
const DRILLING_CIRCULATING_PRESSURE_APP_ID_PROD = 63;

// Drilling QA Apps:
const DRILLING_ASSET_STATUS_APP_ID_QA = 237;
const DRILLING_RIG_OPERATIONS_APP_ID_QA = 216;
const DRILLING_KPI_VISUALIZER_APP_ID_QA = 406;
const DRILLING_ROP_HEATMAP_APP_ID_QA = 182;
const DRILLING_LEADERBOARD_APP_ID_QA = 437;
const DRILLING_TRIPPING_SPEEDS_APP_ID_QA = 375;
const DRILLING_TRACES_APP_ID_QA = 238;
const DRILLING_TOOLFACE_VS_MEASURED_DEPTH_APP_ID_QA = 310;
const DRILLING_BUCKLING_LOAD_ANALYSIS_APP_ID_QA = 175;
const DRILLING_BHA_OPTIMIZATION_APP_ID_QA = 34599;
const DRILLING_DIRECTIONAL_DIVERGENCE_APP_ID_QA = 188;
const DRILLING_CIRCULATING_PRESSURE_TREND_APP_ID_QA = 207;
const DRILLING_ROTARY_TREND_ANALYSIS_APP_ID_QA = 329;
const DRILLING_SURGE_AND_SWAB_APP_ID_QA = 328;
const DRILLING_BUCKLING_LOAD_APP_ID_QA = 175;
const DRILLING_CIRCULATING_PRESSURE_APP_ID_QA = 207;

export const ENABLING_ON_QA_APP_IDS_LIST = [
  DIRECTIONAL_DIVERGENCE_APP_ID_QA,
  TVS_VS_MD_APP_ID_QA,
  RIG_OPERATIONS_APP_ID_QA,
  ASSET_STATUS_APP_ID_QA,
  NPT_EVENTS_APP_ID_QA,
  STAGE_DESIGN_V_ACTUAL_APP_ID_QA,
  PRESSURE_RATE_COMPARISON_APP_ID_QA,
  WELL_COMPARISON_APP_ID_QA,
  ACTIVITY_DETECTION_APP_ID_QA,
  TIME_ANALYSIS_APP_ID_QA,
  TRIPPING_SPEEDS_APP_ID_QA,
  WIRELINE_TRACES_APP_ID_QA,
  SWAP_OVER_TIMES_APP_ID_QA,
  FLUSH_APP_ID_QA,
  DRILLOUT_PARAMETER_SHEET_APP_ID_QA,
  PAD_METRICS_APP_ID_QA,
  KPI_VISUALIZER_APP_ID_QA,
  DRILLOUT_TRACES_APP_ID_QA,

  // Drilling Apps:
  DRILLING_ASSET_STATUS_APP_ID_QA,
  DRILLING_RIG_OPERATIONS_APP_ID_QA,
  DRILLING_KPI_VISUALIZER_APP_ID_QA,
  DRILLING_ROP_HEATMAP_APP_ID_QA,
  DRILLING_LEADERBOARD_APP_ID_QA,
  DRILLING_TRIPPING_SPEEDS_APP_ID_QA,
  DRILLING_TRACES_APP_ID_QA,
  DRILLING_TOOLFACE_VS_MEASURED_DEPTH_APP_ID_QA,
  DRILLING_BUCKLING_LOAD_ANALYSIS_APP_ID_QA,
  DRILLING_BHA_OPTIMIZATION_APP_ID_QA,
  DRILLING_DIRECTIONAL_DIVERGENCE_APP_ID_QA,
  DRILLING_CIRCULATING_PRESSURE_TREND_APP_ID_QA,
  DRILLING_ROTARY_TREND_ANALYSIS_APP_ID_QA,
  DRILLING_SURGE_AND_SWAB_APP_ID_QA,
  DRILLING_BUCKLING_LOAD_APP_ID_QA,
  DRILLING_CIRCULATING_PRESSURE_APP_ID_QA,
];

const DIRECTIONAL_DIVERGENCE_APP_ID_PROD = 40;
const TVS_VS_MD_APP_ID_PROD = 156;
const RIG_OPERATIONS_APP_ID_PROD = 32;
const ASSET_STATUS_APP_ID_PROD = 84;
const NPT_EVENTS_APP_ID_PROD = 137;
const STAGE_DESIGN_V_ACTUAL_APP_ID_PROD = 157;
const PRESSURE_RATE_COMPARISON_APP_ID_PROD = 158;
const WELL_COMPARISON_APP_ID_PROD = 160;
const ACTIVITY_DETECTION_APP_ID_PROD = 159;
const TIME_ANALYSIS_APP_ID_PROD = 164;
const TRIPPING_SPEEDS_APP_ID_PROD = 139;
const WIRELINE_TRACES_APP_ID_PROD = 168;
const SWAP_OVER_TIMES_APP_ID_PROD = 178;
const FLUSH_APP_ID_PROD = 181;
const DRILLOUT_PARAMETER_SHEET_APP_ID_PROD = 183;
const PAD_METRICS_APP_ID_PROD = 187;
const KPI_VISUALIZER_APP_ID_PROD = 196;
const DRILLOUT_TRACES_APP_ID_PROD = 208;

export const ENABLING_ON_PROD_APP_IDS_LIST = [
  DIRECTIONAL_DIVERGENCE_APP_ID_PROD,
  TVS_VS_MD_APP_ID_PROD,
  RIG_OPERATIONS_APP_ID_PROD,
  ASSET_STATUS_APP_ID_PROD,
  NPT_EVENTS_APP_ID_PROD,
  STAGE_DESIGN_V_ACTUAL_APP_ID_PROD,
  PRESSURE_RATE_COMPARISON_APP_ID_PROD,
  WELL_COMPARISON_APP_ID_PROD,
  ACTIVITY_DETECTION_APP_ID_PROD,
  TIME_ANALYSIS_APP_ID_PROD,
  TRIPPING_SPEEDS_APP_ID_PROD,
  WIRELINE_TRACES_APP_ID_PROD,
  SWAP_OVER_TIMES_APP_ID_PROD,
  FLUSH_APP_ID_PROD,
  DRILLOUT_PARAMETER_SHEET_APP_ID_PROD,
  PAD_METRICS_APP_ID_PROD,
  KPI_VISUALIZER_APP_ID_PROD,
  DRILLOUT_TRACES_APP_ID_PROD,

  // Drilling Apps:
  DRILLING_ASSET_STATUS_APP_ID_PROD,
  DRILLING_RIG_OPERATIONS_APP_ID_PROD,
  DRILLING_KPI_VISUALIZER_APP_ID_PROD,
  DRILLING_ROP_HEATMAP_APP_ID_PROD,
  DRILLING_LEADERBOARD_APP_ID_PROD,
  DRILLING_TRIPPING_SPEEDS_APP_ID_PROD,
  DRILLING_TRACES_APP_ID_PROD,
  DRILLING_TOOLFACE_VS_MEASURED_DEPTH_APP_ID_PROD,
  DRILLING_BUCKLING_LOAD_ANALYSIS_APP_ID_PROD,
  DRILLING_BHA_OPTIMIZATION_APP_ID_PROD,
  DRILLING_DIRECTIONAL_DIVERGENCE_APP_ID_PROD,
  DRILLING_CIRCULATING_PRESSURE_TREND_APP_ID_PROD,
  DRILLING_ROTARY_TREND_ANALYSIS_APP_ID_PROD,
  DRILLING_SURGE_AND_SWAB_APP_ID_PROD,
  DRILLING_BUCKLING_LOAD_APP_ID_PROD,
  DRILLING_CIRCULATING_PRESSURE_APP_ID_PROD,
];
