name: branch deletion flow
on:
  delete:

jobs:
  branch-deletion-flow:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'feat/') || startsWith(github.event.ref, 'fix/')
    steps:
      - name: branch deletion flow
        uses: corva-ai/gh-actions/shared-dc-workflows/feat-fix-delete@develop
        with:
          qa-api-key: ${{ secrets.API_KEY_QA }}
          prod-api-key: ${{ secrets.API_KEY }}
          prod-app-key: shell.hypercare.ui
