import sortBy from 'lodash/sortBy';

import { SEGMENTS } from './segment';

export const EVENTS = {
  BHA: 'bha',
  TOP_DRIVE: 'top drive',
  MUD_PUMPS: 'mud pumps',
  STUCK_PIPE: 'stuck pipe',
  PACK_OFF: 'packoff',
  WASHOUT: 'washout',
  BUILD_RATES: 'build rates',
  MWD: 'MWD',
  BOP: 'BOP',
  WEATHER: 'weather',
  RIG_SERVICE: 'rig service',
  SIDETRACK: 'geological sidetrack',
  LOSSES: 'losses',
  H2S: 'H2S',
  WELL_CONTROL: 'well control',
  WAITING_ON_ORDERS: 'waiting on orders',
  WIRELINE_OPERATIONS: 'wireline operations',
  DIRECTIONAL: 'directional',
  GEOLOGY: 'geology',
  FISHING: 'fishing',
  JARRING: 'jarring',
  WAITING_ON_3RD_PARTY: 'waiting on 3rd party',
  WATER_SHORTAGE: 'water shortage',
  WAITING_ON_PROPPANT: 'waiting on proppant',
  WAITING_ON_CHEMICALS: 'waiting on chemicals',
  PLUG_ISSUE: 'plug issue',
  PRODUCTIVE_TIME: 'productive time',
  SCREENOUT: 'screenout',
  OTHER: 'other',
  PUMP_MAINTENANCE: 'pump maintenance',
  WELL_INTERVENTION: 'well intervention',
  PRESSURE_TEST_FAILURE: 'pressure test failure',
  WATER_TRANSFER_ISSUE: 'water transfer issue',
  FRAC_STACK_MAINTENANCE: 'frac stack maintenance',
};

export const EVENTS_METADATA = {
  [EVENTS.BHA]: {
    value: EVENTS.BHA,
    label: 'BHA',
    color: '#e30066',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.TOP_DRIVE]: {
    value: EVENTS.TOP_DRIVE,
    label: 'Top Drive',
    color: '#ffbb37',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.MUD_PUMPS]: {
    value: EVENTS.MUD_PUMPS,
    label: 'Mud Pumps',
    color: '#9500b7',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.STUCK_PIPE]: {
    value: EVENTS.STUCK_PIPE,
    label: 'Stuck Pipe',
    color: '#f70000',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.PACK_OFF]: {
    value: EVENTS.PACK_OFF,
    label: 'Pack Off',
    color: '#ff3e02',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.WASHOUT]: {
    value: EVENTS.WASHOUT,
    label: 'Washout',
    color: '#ff237b',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.BUILD_RATES]: {
    value: EVENTS.BUILD_RATES,
    label: 'Build Rates',
    color: '#ffd200',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.MWD]: {
    value: EVENTS.MWD,
    label: 'MWD',
    color: '#4bd984',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.BOP]: {
    value: EVENTS.BOP,
    label: 'BOP',
    color: '#b74bef',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.WEATHER]: {
    value: EVENTS.WEATHER,
    label: 'Weather',
    color: '#8119FF',
    categories: [SEGMENTS.COMPLETION, SEGMENTS.DRILLING],
  },
  [EVENTS.RIG_SERVICE]: {
    value: EVENTS.RIG_SERVICE,
    label: 'Rig Service',
    color: '#9387f5',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.SIDETRACK]: {
    value: EVENTS.SIDETRACK,
    label: 'Sidetrack',
    color: '#a55d84',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.LOSSES]: {
    value: EVENTS.LOSSES,
    label: 'Losses',
    color: '#f28ac2',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.H2S]: {
    value: EVENTS.H2S,
    label: 'H2S',
    color: '#7d5c4c',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.WELL_CONTROL]: {
    value: EVENTS.WELL_CONTROL,
    label: 'Well Control',
    color: '#9c500c',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.WAITING_ON_ORDERS]: {
    value: EVENTS.WAITING_ON_ORDERS,
    label: 'Waiting On Orders',
    color: '#99e2bb',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.WIRELINE_OPERATIONS]: {
    value: EVENTS.WIRELINE_OPERATIONS,
    label: 'Wireline Operations',
    color: '#7B6491',
    categories: [SEGMENTS.COMPLETION, SEGMENTS.DRILLING],
  },
  [EVENTS.PUMP_MAINTENANCE]: {
    value: EVENTS.PUMP_MAINTENANCE,
    label: 'Pump Maintenance',
    color: '#a55d84',
    categories: [SEGMENTS.COMPLETION],
  },
  [EVENTS.DIRECTIONAL]: {
    value: EVENTS.DIRECTIONAL,
    label: 'Directional',
    color: '#ea9d23',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.GEOLOGY]: {
    value: EVENTS.GEOLOGY,
    label: 'Geology',
    color: '#cc8af2',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.FISHING]: {
    value: EVENTS.FISHING,
    label: 'Fishing',
    color: '#8f1859',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.JARRING]: {
    value: EVENTS.JARRING,
    label: 'Jarring',
    color: '#7d0625',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.WAITING_ON_3RD_PARTY]: {
    value: EVENTS.WAITING_ON_3RD_PARTY,
    label: 'Waiting on 3rd Party',
    color: '#5d786a',
    categories: [SEGMENTS.DRILLING],
  },
  [EVENTS.WAITING_ON_PROPPANT]: {
    value: EVENTS.WAITING_ON_PROPPANT,
    label: 'Waiting on Proppant',
    color: '#f28ac2',
    categories: [SEGMENTS.COMPLETION],
  },
  [EVENTS.WAITING_ON_CHEMICALS]: {
    value: EVENTS.WAITING_ON_CHEMICALS,
    label: 'Wating on Chemicals',
    color: '#7d5c4c',
    categories: [SEGMENTS.COMPLETION],
  },
  [EVENTS.PLUG_ISSUE]: {
    value: EVENTS.PLUG_ISSUE,
    label: 'Plug Issue',
    color: '#00dd00',
    categories: [SEGMENTS.COMPLETION],
  },
  [EVENTS.PRODUCTIVE_TIME]: {
    value: EVENTS.PRODUCTIVE_TIME,
    label: 'Productive Time',
    color: '#99e2bb',
    categories: [SEGMENTS.COMPLETION],
  },
  [EVENTS.SCREENOUT]: {
    value: EVENTS.SCREENOUT,
    label: 'Screenout',
    color: '#ea9d23',
    categories: [SEGMENTS.COMPLETION],
  },
  [EVENTS.WELL_INTERVENTION]: {
    value: EVENTS.WELL_INTERVENTION,
    label: 'Well Intervention',
    color: '#cccc00',
    categories: [SEGMENTS.COMPLETION],
  },
  [EVENTS.PRESSURE_TEST_FAILURE]: {
    value: EVENTS.PRESSURE_TEST_FAILURE,
    label: 'Pressure Test Failure',
    color: '#8f1859',
    categories: [SEGMENTS.COMPLETION],
  },
  [EVENTS.WATER_TRANSFER_ISSUE]: {
    value: EVENTS.WATER_TRANSFER_ISSUE,
    label: 'Water Transfer Issue',
    color: '#777de3',
    categories: [SEGMENTS.COMPLETION],
  },
  [EVENTS.FRAC_STACK_MAINTENANCE]: {
    value: EVENTS.FRAC_STACK_MAINTENANCE,
    label: 'Frac Stack Maintenance',
    color: '#1cdeff',
    categories: [SEGMENTS.COMPLETION],
  },
  [EVENTS.OTHER]: {
    value: EVENTS.OTHER,
    label: 'Other',
    color: '#D2DFD8',
    categories: [SEGMENTS.COMPLETION, SEGMENTS.DRILLING],
  },
};

export const EVENTS_METADATA_LIST = sortBy(Object.values(EVENTS_METADATA), 'label');
