/**
 * This is a real example of the props that'll come
 * to the App component. You'll need to manually update it
 * if in the future some new properties are added
 */

export const mockAppProps = {
  onSettingChange: jest.fn(),
  onSettingsChange: jest.fn(),
  setIsFullscreenModalMode: jest.fn(),
  setIsMaximized: jest.fn(),
  setMainMenuItems: jest.fn(),
  setSecondaryMenuItems: jest.fn(),
  isExampleCheckboxChecked: true,
  app: {
    id: -1,
    app: {
      app_key: 'corva.app_key.ui',
      platform: 'dev_center',
    },
    settings: {
      package: '0.1.0',
      rigId: 1,
      wellId: 2,
      isExampleCheckboxChecked: true,
    },
    package: {
      manifest: {
        format: 1,
        license: {
          type: 'MIT',
          url: 'https://www.oandgexample.com/license/',
        },
        developer: {
          name: 'company name',
          identifier: 'companyIdentifier',
          authors: [],
        },
        application: {
          type: 'ui',
          key: 'corva.app_key.ui',
          visibility: 'private',
          name: 'dc app name',
          description: 'This is the description of my app. You can do great things with it!',
          summary: 'More information about this app goes here',
          category: 'analytics',
          website: 'https://www.oandgexample.com/my-app/',
          segments: ['drilling', 'completion'],
          ui: {
            initial_size: {
              w: 4,
              h: 10,
            },
          },
        },
        settings: {
          entrypoint: {
            file: 'src/index.js',
            function: 'handler',
          },
          environment: {},
          runtime: 'ui',
          app: {
            scheduler_type: 1,
            cron_string: '*/5 * * * *',
          },
        },
        datasets: {},
      },
      build: 'corva.app_key.ui-0.1.0',
      version: '0.1.0',
    },
  },
  package: '0.1.0',
  rigId: 1,
  wellId: 2,
  well: {
    name: 'well name 1',
    settings: {
      basin: 'Delaware',
      county: 'Pecos',
      timezone: 'America/Chicago',
      top_hole: {
        raw: '50.000000,-102.000000',
        coordinates: [50.0, -102.0],
      },
      api_number: '11-222-33333',
      bottom_hole: {},
      mud_company: 'MudCompanyName',
      spud_release: [
        {
          id: '1111111111-2222-aaaa-bbbb-3333333333',
          spud: '01/08/2023 00:46',
          rig_up: '01/08/2023 00:10',
          release: '',
        },
      ],
      string_design: '5',
      contractor_name: 'Unit Drilling',
      target_formation: 'Woodford',
      last_mongo_refresh: '2023-02-23T16:52:58.462Z',
      rig_classification: 'land',
      directional_driller: 'Directional Driller',
      drilling_afe_number: 'AB12345',
      day_shift_start_time: '06:00',
      off_bottom_tolerance: 1,
      target_formation_standard: 'Woodford',
      completion_day_shift_start_time: '06:00',
      associations_last_active_at_updated_at: '2023-02-23T16:52:50.000Z',
    },
    asset_id: 12345678,
    last_active_at: '2023-02-23T16:52:57.000Z',
    id: '2',
    companyId: '1',
  },
  rig: {
    name: 'Some Test Rig Name',
    id: '1',
    asset_id: 9999999,
  },
  coordinates: {
    w: 4,
    h: 10,
    x: 0,
    y: 0,
    pixelHeight: 390,
    pixelWidth: 460,
  },
  currentUser: {
    id: 1,
    company_id: 2,
    first_name: 'John',
    last_name: 'Doe',
    email: 'john.doe@corva.ai',
    mobile: '',
    created_at: '2020-11-03T08:42:53.161Z',
    terms_acceptance_at: '2021-10-20T13:28:1.385Z',
    profile_photo: null,
    recently_viewed_asset_ids: [1],
    unit_system: null,
    role: 'developeradmin',
    title: null,
    group: null,
    favorite_asset_id: null,
    current_segment: null,
    theme: 'dark',
    messaging_id: '1',
    restricted_assets: [],
    restricted_programs: [],
    settings: {
      favorites: {},
      sms_blacklisted: false,
      restricted_assets: [],
      restricted_programs: [],
      participates_in_beta_apps: false,
      last_new_dashboard_shares_check: '2021-11-24T18:57:13.679Z',
    },
    last_sign_in_at: '2023-02-23T10:19:06.349Z',
    locked_access: false,
    unit_ids: [],
    intercom_admin_id: null,
    resource: [],
    intercom_user_hash: 'intercomUserHash',
    profile_groups: [],
    preference: {
      id: 5,
      user: {
        id: 1,
        company_id: 2,
        first_name: 'John',
        last_name: 'Doe',
        email: 'oleksandr.krupko@corva.ai',
        role: 'developeradmin',
        created_at: '2020-11-03T08:42:53.161Z',
        updated_at: '2023-02-23T12:26:46.835Z',
        recently_viewed_asset_ids: [1],
        unit_system: null,
        mobile: '',
        terms_acceptance_at: '2021-10-20T13:28:1.385Z',
        messaging_id: '1',
        settings: {
          favorites: {},
          sms_blacklisted: false,
          restricted_assets: [],
          restricted_programs: [],
          participates_in_beta_apps: false,
          last_new_dashboard_shares_check: '2021-11-24T18:57:13.679Z',
        },
        theme: 'dark',
        title: null,
        group: null,
        profile_photo: null,
        favorite_asset_id: null,
        current_segment: null,
        state: 'active',
        created_by: null,
        provisioner: 'internal',
        intercom_admin_id: null,
        resource: [],
      },
      push_notifications_enabled: true,
      emails_enabled: true,
      sms_enabled: true,
      alert_levels: ['info', 'warning', 'critical'],
      play_alerts_sound: true,
      show_intercom_icon: true,
      segment: ['drilling', 'completion'],
      disable_create_dashboard: false,
      disable_costs: false,
      disable_documents: false,
      realtime_operation_mode: false,
      disable_file_upload: false,
      stay_on_app_store: false,
    },
    company: {
      id: 2,
      name: 'Corva',
      time_zone: 'America/Chicago',
      language: 'en',
      provider: 'corva',
      unit_system: {
        yp: 'hsf',
        oil: 'bbl',
        area: 'ft2',
        mass: 'lb',
        time: 'min',
        angle: 'deg',
        force: 'klbf',
        power: 'hp',
        speed: 'ft/min',
        length: 'm',
        system: 'imperial',
        torque: 'ft-klbf',
        volume: 'gal',
        current: 'mA',
        density: 'ppg',
        gravity: 'g',
        voltage: 'mV',
        porosity: 'pu',
        pressure: 'psi',
        velocity: 'ft/min',
        gasVolume: 'Mscf',
        gravityRMS: 'gRMS',
        msePressure: 'ksi',
        oilFlowRate: 'bbl/min',
        resistivity: 'ohmm',
        shortLength: 'in',
        temperature: 'F',
        massFlowRate: 'lb/min',
        permiability: 'md',
        concentration: 'ppm',
        fluidVelocity: 'ft/min',
        massPerLength: 'lb-ft',
        anglePerLength: 'dp100f',
        lengthPerAngle: 'in/rev',
        volumeFlowRate: 'gal/min',
        angularVelocity: 'rpm',
        inversePressure: 'i-psi',
        acousticSlowness: 'us/ft',
        formationDensity: 'g/l',
        gasConcentration: 'Units (0-5000u)',
        pressureGradient: 'psi/ft',
        massConcentration: 'lb/gal',
        revolutionPerVolume: 'rpg',
        spontaneousPotential: 'mV',
        chemMassConcentration: 'lb/Mgal',
        chemVolumeConcentration: 'gal/Mgal',
      },
      dev_center_enabled: true,
      workflows_enabled: true,
      with_subscription: false,
      competitor_analysis_enabled: true,
    },
    groups: [
      {
        id: 5,
        name: 'developeradmin',
        company_id: 2,
      },
      {
        id: 9,
        name: 'corvaadmin',
        company_id: 2,
      },
    ],
  },
  devCenterRouter: {
    location: {
      pathname: '/app',
      query: {},
    },
  },
  appHeaderProps: {
    app: {
      id: -1,
      app: {
        app_key: 'corva.app_key.ui',
        platform: 'dev_center',
      },
      settings: {
        package: '0.1.0',
        rigId: 1,
        wellId: 2,
        isExampleCheckboxChecked: true,
      },
      package: {
        manifest: {
          format: 1,
          license: {
            type: 'MIT',
            url: 'https://www.oandgexample.com/license/',
          },
          developer: {
            name: 'company name',
            identifier: 'companyIdentifier',
            authors: [],
          },
          application: {
            type: 'ui',
            key: 'corva.app_key.ui',
            visibility: 'private',
            name: 'dc app name',
            description: 'This is the description of my app. You can do great things with it!',
            summary: 'More information about this app goes here',
            category: 'analytics',
            website: 'https://www.oandgexample.com/my-app/',
            segments: ['drilling', 'completion'],
            ui: {
              initial_size: {
                w: 4,
                h: 10,
              },
            },
          },
          settings: {
            entrypoint: {
              file: 'src/index.js',
              function: 'handler',
            },
            environment: {},
            runtime: 'ui',
            app: {
              scheduler_type: 1,
              cron_string: '*/5 * * * *',
            },
          },
          datasets: {},
        },
        build: 'corva.app_key.ui-0.1.0',
        version: '0.1.0',
      },
    },
    appLastAnnotation: null,
    appSettings: {
      package: '0.1.0',
      rigId: 1,
      wellId: 2,
    },
    coordinates: {
      w: 4,
      h: 10,
      x: 0,
      y: 0,
      pixelHeight: 390,
      pixelWidth: 460,
    },
    currentUser: {
      id: 1,
      company_id: 2,
      first_name: 'John',
      last_name: 'Doe',
      email: 'oleksandr.krupko@corva.ai',
      mobile: '',
      created_at: '2020-11-03T08:42:53.161Z',
      terms_acceptance_at: '2021-10-20T13:28:1.385Z',
      profile_photo: null,
      recently_viewed_asset_ids: [1],
      unit_system: null,
      role: 'developeradmin',
      title: null,
      group: null,
      favorite_asset_id: null,
      current_segment: null,
      theme: 'dark',
      messaging_id: '1',
      restricted_assets: [],
      restricted_programs: [],
      settings: {
        favorites: {},
        sms_blacklisted: false,
        restricted_assets: [],
        restricted_programs: [],
        participates_in_beta_apps: false,
        last_new_dashboard_shares_check: '2021-11-24T18:57:13.679Z',
      },
      last_sign_in_at: '2023-02-23T10:19:06.349Z',
      locked_access: false,
      unit_ids: [],
      intercom_admin_id: null,
      resource: [],
      intercom_user_hash: 'intercomUserHash',
      profile_groups: [],
      preference: {
        id: 5,
        user: {
          id: 1,
          company_id: 2,
          first_name: 'John',
          last_name: 'Doe',
          email: 'oleksandr.krupko@corva.ai',
          role: 'developeradmin',
          created_at: '2020-11-03T08:42:53.161Z',
          updated_at: '2023-02-23T12:26:46.835Z',
          recently_viewed_asset_ids: [1],
          unit_system: null,
          mobile: '',
          terms_acceptance_at: '2021-10-20T13:28:1.385Z',
          messaging_id: '1',
          settings: {
            favorites: {},
            sms_blacklisted: false,
            restricted_assets: [],
            restricted_programs: [],
            participates_in_beta_apps: false,
            last_new_dashboard_shares_check: '2021-11-24T18:57:13.679Z',
          },
          theme: 'dark',
          title: null,
          group: null,
          profile_photo: null,
          favorite_asset_id: null,
          current_segment: null,
          state: 'active',
          created_by: null,
          provisioner: 'internal',
          intercom_admin_id: null,
          resource: [],
        },
        push_notifications_enabled: true,
        emails_enabled: true,
        sms_enabled: true,
        alert_levels: ['info', 'warning', 'critical'],
        play_alerts_sound: true,
        show_intercom_icon: true,
        segment: ['drilling', 'completion'],
        disable_create_dashboard: false,
        disable_costs: false,
        disable_documents: false,
        realtime_operation_mode: false,
        disable_file_upload: false,
        stay_on_app_store: false,
      },
      company: {
        id: 2,
        name: 'Corva',
        time_zone: 'America/Chicago',
        language: 'en',
        provider: 'corva',
        unit_system: {
          yp: 'hsf',
          oil: 'bbl',
          area: 'ft2',
          mass: 'lb',
          time: 'min',
          angle: 'deg',
          force: 'klbf',
          power: 'hp',
          speed: 'ft/min',
          length: 'm',
          system: 'imperial',
          torque: 'ft-klbf',
          volume: 'gal',
          current: 'mA',
          density: 'ppg',
          gravity: 'g',
          voltage: 'mV',
          porosity: 'pu',
          pressure: 'psi',
          velocity: 'ft/min',
          gasVolume: 'Mscf',
          gravityRMS: 'gRMS',
          msePressure: 'ksi',
          oilFlowRate: 'bbl/min',
          resistivity: 'ohmm',
          shortLength: 'in',
          temperature: 'F',
          massFlowRate: 'lb/min',
          permiability: 'md',
          concentration: 'ppm',
          fluidVelocity: 'ft/min',
          massPerLength: 'lb-ft',
          anglePerLength: 'dp100f',
          lengthPerAngle: 'in/rev',
          volumeFlowRate: 'gal/min',
          angularVelocity: 'rpm',
          inversePressure: 'i-psi',
          acousticSlowness: 'us/ft',
          formationDensity: 'g/l',
          gasConcentration: 'Units (0-5000u)',
          pressureGradient: 'psi/ft',
          massConcentration: 'lb/gal',
          revolutionPerVolume: 'rpg',
          spontaneousPotential: 'mV',
          chemMassConcentration: 'lb/Mgal',
          chemVolumeConcentration: 'gal/Mgal',
        },
        dev_center_enabled: true,
        workflows_enabled: true,
        with_subscription: false,
        competitor_analysis_enabled: true,
      },
      groups: [
        {
          id: 5,
          name: 'developeradmin',
          company_id: 2,
        },
        {
          id: 9,
          name: 'corvaadmin',
          company_id: 2,
        },
      ],
    },
    isMaximized: false,
    layoutEnvironment: {
      type: 'general',
      pdfReportMode: false,
    },
    well: {
      name: 'well name 1',
      settings: {
        basin: 'Delaware',
        county: 'Pecos',
        timezone: 'America/Chicago',
        top_hole: {
          raw: '50.000000,-102.000000',
          coordinates: [50.0, -102.0],
        },
        api_number: '11-222-33333',
        bottom_hole: {},
        mud_company: 'MudCompanyName',
        spud_release: [
          {
            id: '1111111111-2222-aaaa-bbbb-3333333333',
            spud: '01/08/2023 00:46',
            rig_up: '01/08/2023 00:10',
            release: '',
          },
        ],
        string_design: '5',
        contractor_name: 'Unit Drilling',
        target_formation: 'Woodford',
        last_mongo_refresh: '2023-02-23T16:52:58.462Z',
        rig_classification: 'land',
        directional_driller: 'Directional Driller',
        drilling_afe_number: 'AB12345',
        day_shift_start_time: '06:00',
        off_bottom_tolerance: 1,
        target_formation_standard: 'Woodford',
        completion_day_shift_start_time: '06:00',
        associations_last_active_at_updated_at: '2023-02-23T16:52:50.000Z',
      },
      asset_id: 12345678,
      last_active_at: '2023-02-23T16:52:57.000Z',
      id: '2',
      companyId: '1',
    },
    rig: {
      name: 'Some Test Rig Name',
      id: '1',
      asset_id: 9999999,
    },
  },
  isNative: false,
  layoutEnvironment: {
    type: 'general',
    pdfReportMode: false,
  },
  // Completion segment app props
  fracFleet: {
    current_pad_id: 101,
    id: 1002,
    name: 'Magic Frac Fleet',
  },
  wells: [
    { id: 1, name: 'Well 1' },
    { id: 2, name: 'Well 2' },
  ],
};
