name: develop branch flow
on:
  push:
    branches:
      - 'develop'

jobs:
  develop-flow:
    runs-on: ubuntu-latest
    steps:
      - name: develop branch flow
        uses: corva-ai/gh-actions/shared-dc-workflows/develop@develop
        with:
          qa-api-key: ${{ secrets.API_KEY_QA }}
          # is-upload-to-prod: true
          # prod-api-key: ${{ secrets.API_KEY }}
          npm-token: ${{ secrets.CORVA_NPM_TOKEN }}
