import { mockActivitesData } from './mockActivitiesData';
import { mockAppProps, mockTestAssetId } from './mockAppProps';
import { mockPreditionsData } from './mockPredictionsData';
import { mockScaleSetting } from './mockScaleSetting';
import { mockWells } from './mockWells';
import { mockWitsData } from './mockWitsData';

export const mockAppData = {
  currentAsset: mockAppProps.wells[0],
  mainData: [
    {
      aictivities: mockActivitesData,
      asset_id: mockTestAssetId,
      asset_name: mockWells[0].name,
      is_offset: false,
      misc: {
        lineStyle: 'solid',
        lineWidth: 2,
        alpha: 1,
      },
      predictions: mockPreditionsData,
      strage_number: 25,
      wits: mockWitsData,
    },
  ],
  witsSubData: {
    _id: '646fd0490d7b37003fca678d',
    version: 1,
    provider: 'corva',
    collection: 'completion.wits',
    timestamp: 1684174506,
    asset_id: 70321078,
    company_id: 15,
    stage_number: 25,
    data: {
      clean_flow_rate_in_streamed: 0.344,
      total_clean_volume_in_streamed: 13621.599,
      total_slurry_volume_in_streamed: 14610.328,
      proppant_1_mass_streamed: 616692.352,
      elapsed_time: 12666,
      clean_flow_rate_in: 2.212,
      total_clean_volume_in: 13959.7503,
      total_slurry_volume_in: 14627.5246,
      total_chemical_rate_in: 0,
      total_friction_reducer: 0,
      total_proppant_concentration: 0,
      total_proppant_mass: 620256.3234,
      bottomhole_proppant_concentration: 0.001,
      hydrostatic_pressure: 4116.7273,
      inverse_hydrostatic_pressure: 0.0002,
      pipe_frictional_pressure_loss: 21933.09,
      nwb_frictional_pressure_loss: 0.86,
      bottomhole_pressure: -17817.22,
      net_pressure: -24233.05,
      hydraulic_horse_power: 0,
      friction_reducer: 0,
      powder_breaker: 0,
      proppant_1_concentration: 0,
      proppant_1_mass: 616692.352,
      wellhead_pressure: 0,
      slurry_flow_rate_in: 2.212,
      extra_clean_fluid: 0.0369,
      cumulative_chemicals: {
        friction_reducer: 483.1165,
        powder_breaker: 136.4661,
        total_friction_reducer: 483.1165,
      },
      timestamp: 1684174506,
      is_valid: true,
      'offset_pressure_2smh-2_int': 0,
      pumpside_pressure: 263.494,
      'offset_pressure_2smh-2_zipper': 0,
      'offset_pressure_3mh-2_zipper': 0,
      'offset_pressure_3mh-2_int': 3.987,
    },
  },
  appScaleSetting: mockScaleSetting,
  appFilterSetting: {
    stageMode: 'active',
    lastCustomTime: '0.5',
    customActiveMode: 5,
    viewMode: 'series',
    manualStages: [],
    refPoint: 'isip',
  },
  mappedChemicals: [
    {
      name: 'Liquid FR',
      color: '#FFA891',
      key: 'friction_reducer',
      unitType: 'chemVolumeConcentration',
      unit: 'gal/Mgal',
      precision: 2,
      category: 'chemical',
    },
    {
      name: 'Total Liquid FR',
      color: '#FF91A8',
      key: 'total_friction_reducer',
      unitType: 'chemVolumeConcentration',
      unit: 'gal/Mgal',
      precision: 2,
      category: 'chemical',
    },
    {
      name: 'Powder Breaker',
      color: '#c732b8',
      key: 'powder_breaker',
      unitType: 'chemMassConcentration',
      unit: 'lb/Mgal',
      precision: 2,
      category: 'chemical',
    },
  ],
  offsetPressures: [
    {
      key: 'offset_pressure_3mh-2_int',
      name: '3MH-2 INT',
      unitType: 'pressure',
      unit: 'psi',
      color: '#73AFAA',
      axisId: 'offsetPressure',
      category: 'offsetPressure',
      collection: 'wits',
      precision: 0,
    },
    {
      key: 'offset_pressure_2smh-2_int',
      name: '2SMH-2 INT',
      unitType: 'pressure',
      unit: 'psi',
      color: '#51A8BA',
      axisId: 'offsetPressure',
      category: 'offsetPressure',
      collection: 'wits',
      precision: 0,
    },
    {
      key: 'offset_pressure_3mh-2_zipper',
      name: '3MH-2 ZIPPER',
      unitType: 'pressure',
      unit: 'psi',
      color: '#1C8195',
      axisId: 'offsetPressure',
      category: 'offsetPressure',
      collection: 'wits',
      precision: 0,
    },
    {
      key: 'offset_pressure_2smh-2_zipper',
      name: '2SMH-2 ZIPPER',
      unitType: 'pressure',
      unit: 'psi',
      color: '#006073',
      axisId: 'offsetPressure',
      category: 'offsetPressure',
      collection: 'wits',
      precision: 0,
    },
  ],
  rtValues: [
    {
      name: 'Wellhead Pressure',
      key: 'wellhead_pressure',
      unitType: 'pressure',
      unit: 'psi',
      color: '#F50057',
      precision: 0,
      category: 'pressure',
      collection: 'wits',
    },
    {
      name: 'Pipe Frictional Presure Loss',
      key: 'pipe_frictional_pressure_loss',
      unitType: 'pressure',
      unit: 'psi',
      color: '#D8496B',
      precision: 0,
      category: 'pressure',
      collection: 'wits',
    },
    {
      name: 'NWB Frictional Pressure Loss',
      key: 'nwb_frictional_pressure_loss',
      unitType: 'pressure',
      unit: 'psi',
      color: '#807DFF',
      precision: 0,
      category: 'pressure',
      collection: 'wits',
    },
    {
      name: 'Bottomhole Pressure',
      key: 'bottomhole_pressure',
      unitType: 'pressure',
      unit: 'psi',
      color: '#4DCFB3',
      precision: 0,
      category: 'pressure',
      collection: 'wits',
    },
    {
      name: 'Net Pressure',
      key: 'net_pressure',
      unitType: 'pressure',
      unit: 'psi',
      color: '#EE752F',
      precision: 0,
      category: 'pressure',
      collection: 'wits',
    },
    {
      name: 'Hydrostatic Pressure',
      key: 'hydrostatic_pressure',
      unitType: 'pressure',
      unit: 'psi',
      color: '#E458C8',
      precision: 0,
      category: 'pressure',
      collection: 'wits',
    },
  ],
};
