export const mockScaleSetting = [
  {
    key: 'pressure',
    label: 'Pressure',
    unitType: 'pressure',
    unit: 'psi',
    series: [
      {
        name: 'Wellhead Pressure',
        key: 'wellhead_pressure',
        unitType: 'pressure',
        unit: 'psi',
        color: '#F50057',
        precision: 0,
        category: 'pressure',
      },
      {
        name: 'Pipe Frictional Presure Loss',
        key: 'pipe_frictional_pressure_loss',
        unitType: 'pressure',
        unit: 'psi',
        color: '#D8496B',
        precision: 0,
        category: 'pressure',
      },
      {
        name: 'NWB Frictional Pressure Loss',
        key: 'nwb_frictional_pressure_loss',
        unitType: 'pressure',
        unit: 'psi',
        color: '#807DFF',
        precision: 0,
        category: 'pressure',
      },
      {
        name: 'Bottomhole Pressure',
        key: 'bottomhole_pressure',
        unitType: 'pressure',
        unit: 'psi',
        color: '#4DCFB3',
        precision: 0,
        category: 'pressure',
      },
      {
        name: 'Net Pressure',
        key: 'net_pressure',
        unitType: 'pressure',
        unit: 'psi',
        color: '#EE752F',
        precision: 0,
        category: 'pressure',
      },
      {
        name: 'Pumpside Pressure',
        key: 'pumpside_pressure',
        unitType: 'pressure',
        unit: 'psi',
        color: '#855CF8',
        precision: 0,
        category: 'pressure',
      },
    ],
    min: 0,
  },
  {
    key: 'backsidePressure',
    label: 'Backside Pressure',
    unitType: 'pressure',
    unit: 'psi',
    series: [
      {
        name: 'Backside Pressure',
        key: 'backside_pressure',
        unitType: 'pressure',
        unit: 'psi',
        color: '#32aa32',
        precision: 0,
        category: 'pressure',
      },
    ],
    min: 0,
  },
  {
    key: 'hydrostaticPressure',
    label: 'Hydrostatic Pressure',
    unitType: 'pressure',
    unit: 'psi',
    series: [
      {
        name: 'Hydrostatic Pressure',
        key: 'hydrostatic_pressure',
        unitType: 'pressure',
        unit: 'psi',
        color: '#E458C8',
        precision: 0,
        category: 'pressure',
      },
    ],
    min: 0,
  },
  {
    key: 'offsetPressure',
    label: 'Offset Pressure',
    unitType: 'pressure',
    unit: 'psi',
    series: [
      {
        key: 'offset_pressure_3mh-2_int',
        name: '3MH-2 INT',
        unitType: 'pressure',
        unit: 'psi',
        color: '#73AFAA',
        axisId: 'offsetPressure',
        category: 'offsetPressure',
        collection: 'wits',
        precision: 0,
      },
      {
        key: 'offset_pressure_2smh-2_int',
        name: '2SMH-2 INT',
        unitType: 'pressure',
        unit: 'psi',
        color: '#51A8BA',
        axisId: 'offsetPressure',
        category: 'offsetPressure',
        collection: 'wits',
        precision: 0,
      },
      {
        key: 'offset_pressure_3mh-2_zipper',
        name: '3MH-2 ZIPPER',
        unitType: 'pressure',
        unit: 'psi',
        color: '#1C8195',
        axisId: 'offsetPressure',
        category: 'offsetPressure',
        collection: 'wits',
        precision: 0,
      },
      {
        key: 'offset_pressure_2smh-2_zipper',
        name: '2SMH-2 ZIPPER',
        unitType: 'pressure',
        unit: 'psi',
        color: '#006073',
        axisId: 'offsetPressure',
        category: 'offsetPressure',
        collection: 'wits',
        precision: 0,
      },
    ],
    min: 0,
  },
  {
    key: 'rate',
    label: 'Flow Rate',
    unitType: 'oilFlowRate',
    unit: 'bbl/min',
    series: [
      {
        name: 'Clean Flow Rate',
        key: 'clean_flow_rate_in',
        unitType: 'oilFlowRate',
        unit: 'bbl/min',
        color: '#7CC900',
        precision: 1,
        category: 'rate',
      },
      {
        name: 'Slurry Flow Rate',
        key: 'slurry_flow_rate_in',
        unitType: 'oilFlowRate',
        unit: 'bbl/min',
        color: '#64B5FF',
        precision: 1,
        category: 'rate',
      },
    ],
    min: 0,
  },
  {
    key: 'chemVolumeConcentration',
    label: 'Chemical Vol',
    unitType: 'chemVolumeConcentration',
    unit: 'gal/Mgal',
    series: [
      {
        name: 'Liquid Gel',
        color: '#84F4F7',
        key: 'gel',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Acid',
        color: '#6ec732',
        key: 'acid',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Liquid FR',
        color: '#FFA891',
        key: 'friction_reducer',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Liquid FR Extra',
        color: '#91FFA8',
        key: 'friction_reducer_extra',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Total Liquid FR',
        color: '#FF91A8',
        key: 'total_friction_reducer',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Fluid Loss',
        color: '#c7bd32',
        key: 'fluid_loss',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Cross Linker',
        color: '#B0CA87',
        key: 'cross_linker',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Liquid EB',
        color: '#32b8c7',
        key: 'enzyme_breaker',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Polymer Plug',
        color: '#9fc732',
        key: 'ploymer_plug',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Acid Inhibitor',
        color: '#AB9081',
        key: 'acid_inhibitor',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Acid Retarder',
        color: '#7CC6FE',
        key: 'acid_retarder',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Emulsifier',
        color: '#5DFDCB',
        key: 'emulsifier',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Clay Stabilizer',
        color: '#9C6B20',
        key: 'clay_stabilizer',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Surfactant',
        color: '#FFF689',
        key: 'surfactant',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Non-Emulsifier',
        color: '#C0DF85',
        key: 'non_emulsifier',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Fines Suspender',
        color: '#7B8E55',
        key: 'fines_suspender',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Anti-Sludge',
        color: '#07393C',
        key: 'anti_sludge',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Scale Inhibitor',
        color: '#C0E5CA',
        key: 'scale_inhibitor',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Iron Control',
        color: '#CD5334',
        key: 'iron_control',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Oxygen Scavenger',
        color: '#DFF283',
        key: 'oxygen_scavenger',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Mutual Solvent',
        color: '#ad5ec7',
        key: 'mutual_solvent',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Corrosion Inhibitor',
        color: '#7C2209',
        key: 'corrosion_inhibitor',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Paraffin Control',
        color: '#F5A65B',
        key: 'paraffin_control',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Biocide',
        color: '#E9B76A',
        key: 'biocide',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'PH Adjusting Agent',
        color: '#519872',
        key: 'ph_adjusting_agent',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Accelerator',
        color: '#5E3023',
        key: 'accelerator',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Instant Crosslinker',
        color: '#6E6E23',
        key: 'instant_crosslinker',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Delayed Crosslinker',
        color: '#7E306E',
        key: 'delayed_crosslinker',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Liquid Breaker',
        color: '#233023',
        key: 'liquid_breaker',
        unitType: 'chemVolumeConcentration',
        unit: 'gal/Mgal',
        precision: 2,
        category: 'chemical',
      },
    ],
    min: 0,
  },
  {
    key: 'chemMassConcentration',
    label: 'Chemical Mass',
    unitType: 'chemMassConcentration',
    unit: 'lb/Mgal',
    series: [
      {
        name: 'Diverter',
        color: '#BB9394',
        key: 'divertor',
        unitType: 'chemMassConcentration',
        unit: 'lb/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Powder Breaker',
        color: '#c732b8',
        key: 'powder_breaker',
        unitType: 'chemMassConcentration',
        unit: 'lb/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Powder Gel',
        color: '#308E23',
        key: 'powder_gel',
        unitType: 'chemMassConcentration',
        unit: 'lb/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Powder FR',
        color: '#30239E',
        key: 'powder_friction_reducer',
        unitType: 'chemMassConcentration',
        unit: 'lb/Mgal',
        precision: 2,
        category: 'chemical',
      },
      {
        name: 'Powder EB',
        color: '#A32A78',
        key: 'powder_enzyme_breaker',
        unitType: 'chemMassConcentration',
        unit: 'lb/Mgal',
        precision: 2,
        category: 'chemical',
      },
    ],
    min: 0,
  },
  {
    key: 'proppantConc',
    label: 'Proppant Conc',
    unitType: 'massConcentration',
    unit: 'lb/gal',
    series: [
      {
        name: 'Total Proppant Conc',
        key: 'total_proppant_concentration',
        unitType: 'massConcentration',
        unit: 'lb/gal',
        color: '#FF8F0B',
        precision: 2,
        category: 'proppant',
      },
      {
        name: 'BHPC',
        key: 'bottomhole_proppant_concentration',
        unitType: 'massConcentration',
        unit: 'lb/gal',
        color: '#9F4BED',
        precision: 2,
        category: 'proppant',
      },
      {
        name: 'Proppant 1 Conc',
        key: 'proppant_1_concentration',
        unitType: 'massConcentration',
        unit: 'lb/gal',
        color: '#7EB93A',
        precision: 2,
        category: 'proppant',
      },
      {
        name: 'Proppant 2 Conc',
        key: 'proppant_2_concentration',
        unitType: 'massConcentration',
        unit: 'lb/gal',
        color: '#6785E8',
        precision: 2,
        category: 'proppant',
      },
    ],
    min: 0,
  },
  {
    key: 'proppantMass',
    label: 'Proppant Mass',
    unitType: 'mass',
    unit: 'lb',
    series: [
      {
        name: 'Total Proppant Mass',
        key: 'total_proppant_mass',
        unitType: 'mass',
        color: '#EE964B',
        unit: 'lb',
        precision: 2,
        category: 'proppant',
      },
      {
        name: 'Proppant 1 Volume',
        key: 'proppant_1_mass',
        unitType: 'mass',
        color: '#C6C013',
        unit: 'lb',
        precision: 2,
        category: 'proppant',
      },
      {
        name: 'Proppant 2 Volume',
        key: 'proppant_2_mass',
        unitType: 'mass',
        color: '#7ff577',
        unit: 'lb',
        precision: 2,
        category: 'proppant',
      },
    ],
    min: 0,
  },
  {
    key: 'totalVolume',
    label: 'Total Volume',
    unitType: 'oil',
    unit: 'bbl',
    series: [
      {
        name: 'Clean Volume',
        key: 'total_clean_volume_in',
        unitType: 'oil',
        unit: 'bbl',
        color: '#257CFF',
        precision: 0,
        category: 'totalVolume',
      },
      {
        name: 'Slurry Volume',
        key: 'total_slurry_volume_in',
        unitType: 'oil',
        unit: 'bbl',
        color: '#7169AE',
        precision: 0,
        category: 'totalVolume',
      },
    ],
    min: 0,
  },
  {
    key: 'trashChannels',
    label: 'Trash Channels',
    series: [],
  },
];
