import { mockTestAssetId } from './mockAppProps';

export const mockWitsData = [
  {
    _id: '646fcd02009082003e50d98e',
    timestamp: 1684161849,
    asset_id: mockTestAssetId,
    stage_number: 25,
    data: {
      clean_flow_rate_in_streamed: 0.095,
      total_clean_volume_in_streamed: 1.246,
      total_slurry_volume_in_streamed: 3.674,
      proppant_1_mass_streamed: 0,
      elapsed_time: 4.5,
      clean_flow_rate_in: 0.024,
      total_clean_volume_in: 0.0024,
      total_slurry_volume_in: 0.0024,
      total_chemical_rate_in: 0,
      total_friction_reducer: 0,
      total_proppant_concentration: 0,
      total_proppant_mass: 0,
      bottomhole_proppant_concentration: 0,
      hydrostatic_pressure: 4115.9135,
      inverse_hydrostatic_pressure: 0.0002,
      pipe_frictional_pressure_loss: 237.97,
      nwb_frictional_pressure_loss: 0,
      bottomhole_pressure: 3877.94,
      net_pressure: 0,
      hydraulic_horse_power: 0,
      friction_reducer: 0,
      powder_breaker: 0,
      proppant_1_concentration: 0,
      proppant_1_mass: 0,
      wellhead_pressure: 0,
      slurry_flow_rate_in: 0.024,
      extra_clean_fluid: 0.0004,
      cumulative_chemicals: {
        friction_reducer: 0,
        powder_breaker: 0,
        total_friction_reducer: 0,
      },
      timestamp: 1684161844.5,
      is_valid: 1,
      'offset_pressure_2smh-2_int': 0,
      'offset_pressure_2smh-2_zipper': 0,
      'offset_pressure_3mh-2_zipper': 0,
      'offset_pressure_3mh-2_int': 4.3795,
      pumpside_pressure: 25.1445,
    },
  },
  {
    _id: '646fcd03a18939004e0d2b6d',
    timestamp: 1684161859,
    asset_id: mockTestAssetId,
    stage_number: 25,
    data: {
      clean_flow_rate_in_streamed: 0.0885,
      total_clean_volume_in_streamed: 1.261,
      total_slurry_volume_in_streamed: 3.678,
      proppant_1_mass_streamed: 0,
      elapsed_time: 14.5,
      clean_flow_rate_in: 0.0195,
      total_clean_volume_in: 0.0059,
      total_slurry_volume_in: 0.0059,
      total_chemical_rate_in: 0,
      total_friction_reducer: 0,
      total_proppant_concentration: 0,
      total_proppant_mass: 0,
      bottomhole_proppant_concentration: 0,
      hydrostatic_pressure: 4115.9135,
      inverse_hydrostatic_pressure: 0.0002,
      pipe_frictional_pressure_loss: 193.35,
      nwb_frictional_pressure_loss: 0,
      bottomhole_pressure: 3922.56,
      net_pressure: 0,
      hydraulic_horse_power: 0,
      friction_reducer: 0,
      powder_breaker: 0,
      proppant_1_concentration: 0,
      proppant_1_mass: 0,
      wellhead_pressure: 0,
      slurry_flow_rate_in: 0.0195,
      extra_clean_fluid: 0.0003,
      cumulative_chemicals: {
        friction_reducer: 0,
        powder_breaker: 0,
        total_friction_reducer: 0,
      },
      timestamp: 1684161854.5,
      is_valid: 1,
      'offset_pressure_3mh-2_zipper': 0,
      'offset_pressure_3mh-2_int': 4.164,
      'offset_pressure_2smh-2_int': 0,
      'offset_pressure_2smh-2_zipper': 0,
      pumpside_pressure: 24.2905,
    },
  },
  {
    _id: '646fcd03a18939004e0d2b6e',
    timestamp: 1684161869,
    asset_id: mockTestAssetId,
    stage_number: 25,
    data: {
      clean_flow_rate_in_streamed: 0.087,
      total_clean_volume_in_streamed: 1.2765,
      total_slurry_volume_in_streamed: 3.681,
      proppant_1_mass_streamed: 0,
      elapsed_time: 24.5,
      clean_flow_rate_in: 0.022,
      total_clean_volume_in: 0.0093,
      total_slurry_volume_in: 0.0093,
      total_chemical_rate_in: 0,
      total_friction_reducer: 0,
      total_proppant_concentration: 0,
      total_proppant_mass: 0,
      bottomhole_proppant_concentration: 0,
      hydrostatic_pressure: 4115.9135,
      inverse_hydrostatic_pressure: 0.0002,
      pipe_frictional_pressure_loss: 218.14,
      nwb_frictional_pressure_loss: 0,
      bottomhole_pressure: 3897.77,
      net_pressure: 0,
      hydraulic_horse_power: 0,
      friction_reducer: 0,
      powder_breaker: 0,
      proppant_1_concentration: 0,
      proppant_1_mass: 0,
      wellhead_pressure: 0,
      slurry_flow_rate_in: 0.022,
      extra_clean_fluid: 0.0004,
      cumulative_chemicals: {
        friction_reducer: 0,
        powder_breaker: 0,
        total_friction_reducer: 0,
      },
      timestamp: 1684161864.5,
      is_valid: 1,
      'offset_pressure_2smh-2_int': 0,
      'offset_pressure_2smh-2_zipper': 0,
      'offset_pressure_3mh-2_zipper': 0,
      'offset_pressure_3mh-2_int': 4.054,
      pumpside_pressure: 24.2325,
    },
  },
];
