export const mockCurrentUser = {
  id: 5109,
  company_id: 1,
  first_name: 'Dan',
  last_name: 'Baba',
  email: 'dan.baba@corva.dev',
  mobile: '',
  created_at: '2021-09-13T14:46:47.660Z',
  terms_acceptance_at: '2021-09-15T09:42:55.912Z',
  profile_photo: '',
  recently_viewed_asset_ids: [27257676, 53786727, 32412267],
  unit_system: null,
  role: 'admin',
  title: null,
  group: null,
  favorite_asset_id: null,
  current_segment: 'drilling',
  theme: 'dark',
  messaging_id: 'qa_5109',
  restricted_assets: [],
  restricted_programs: [],
  settings: {
    favorites: {
      rigs: [],
    },
    feed_filters: {
      end_date: '',
      company_id: null,
      start_date: '05/12/23 03:24',
      content_types: [
        'post',
        'completion_operational_note',
        'fluid_report',
        'completion_npt_event',
        'traces_memo',
        'completion_operation_summary',
        'app_annotation',
        'npt_event',
        'operation_summary',
        'survey_station',
        'completion_actual_stage',
        'driller_memo',
        'dvd_comment',
        'completion_daily_cost',
        'well_plan',
        'document',
        'alert',
        'completion_document',
        'operational_note',
        'lessons_learned',
      ],
      selected_rigs_ids: [],
      selected_user_ids: [],
      users_radio_value: 'all',
      assets_radio_value: 'all',
      date_range_radio_value: 'last24hours',
    },
    sms_blacklisted: false,
    favorit_asset_ids: [],
    restricted_assets: [],
    alerts_list_filters: {
      end_date: '',
      segments: ['drilling', 'completion'],
      alert_name: '',
      start_date: '',
      validation: 'all',
      alert_levels: ['info', 'warning', 'critical'],
      subscription: '',
      classification: 'all',
      selected_rigs_id: null,
      assets_radio_value: 'all',
      date_range_radio_value: 'all',
    },
    restricted_programs: [],
    last_new_alerts_check: '2023-05-26T15:49:09.418Z',
    notifications_filters: {
      content_types: ['asset'],
    },
    last_new_feed_items_check: '2023-05-13T01:24:52.839Z',
    participates_in_beta_apps: false,
    last_new_dashboard_shares_check: '2021-11-11T15:16:15.808Z',
  },
  last_sign_in_at: '2023-05-29T11:49:37.058Z',
  locked_access: false,
  unit_ids: [],
  intercom_admin_id: null,
  resource: [],
  intercom_user_hash: 'bcbf45580ce037eef89856feca5f185ddd92b51768426eed4e76278d70000873',
  profile_groups: [],
  preference: {
    id: 5097,
    user: {
      id: 5109,
      company_id: 1,
      first_name: 'Dan',
      last_name: 'Baba',
      email: 'dan.baba@corva.dev',
      role: 'admin',
      created_at: '2021-09-13T14:46:47.660Z',
      updated_at: '2023-06-01T00:05:27.066Z',
      recently_viewed_asset_ids: [27257676, 53786727, 32412267],
      unit_system: null,
      mobile: '',
      terms_acceptance_at: '2021-09-15T09:42:55.912Z',
      messaging_id: 'qa_5109',
      settings: {
        favorites: {
          rigs: [],
        },
        feed_filters: {
          end_date: '',
          company_id: null,
          start_date: '05/12/23 03:24',
          content_types: [
            'post',
            'completion_operational_note',
            'fluid_report',
            'completion_npt_event',
            'traces_memo',
            'completion_operation_summary',
            'app_annotation',
            'npt_event',
            'operation_summary',
            'survey_station',
            'completion_actual_stage',
            'driller_memo',
            'dvd_comment',
            'completion_daily_cost',
            'well_plan',
            'document',
            'alert',
            'completion_document',
            'operational_note',
            'lessons_learned',
          ],
          selected_rigs_ids: [],
          selected_user_ids: [],
          users_radio_value: 'all',
          assets_radio_value: 'all',
          date_range_radio_value: 'last24hours',
        },
        sms_blacklisted: false,
        favorit_asset_ids: [],
        restricted_assets: [],
        alerts_list_filters: {
          end_date: '',
          segments: ['drilling', 'completion'],
          alert_name: '',
          start_date: '',
          validation: 'all',
          alert_levels: ['info', 'warning', 'critical'],
          subscription: '',
          classification: 'all',
          selected_rigs_id: null,
          assets_radio_value: 'all',
          date_range_radio_value: 'all',
        },
        restricted_programs: [],
        last_new_alerts_check: '2023-05-26T15:49:09.418Z',
        notifications_filters: {
          content_types: ['asset'],
        },
        last_new_feed_items_check: '2023-05-13T01:24:52.839Z',
        participates_in_beta_apps: false,
        last_new_dashboard_shares_check: '2021-11-11T15:16:15.808Z',
      },
      theme: 'dark',
      title: null,
      profile_photo: '',
      favorite_asset_id: null,
      current_segment: 'drilling',
      state: 'active',
      created_by: 35,
      provisioner: 'internal',
      intercom_admin_id: null,
      resource: [],
      group: null,
    },
    push_notifications_enabled: true,
    emails_enabled: true,
    sms_enabled: true,
    alert_levels: ['info', 'warning', 'critical'],
    play_alerts_sound: true,
    show_intercom_icon: true,
    segment: ['drilling', 'completion'],
    disable_create_dashboard: false,
    disable_costs: false,
    disable_documents: false,
    realtime_operation_mode: false,
    disable_file_upload: false,
    stay_on_app_store: false,
  },
  company: {
    id: 1,
    name: 'Corva',
    time_zone: 'America/Chicago',
    language: 'en',
    provider: 'corva',
    unit_system: null,
    dev_center_enabled: true,
    workflows_enabled: true,
    with_subscription: true,
    competitor_analysis_enabled: true,
  },
  groups: [
    {
      id: 549,
      name: 'developeradmin',
      company_id: 1,
    },
    {
      id: 550,
      name: 'admin',
      company_id: 1,
    },
    {
      id: 553,
      name: 'corvaadmin',
      company_id: 1,
    },
  ],
};
