import { mockCurrentUser } from './mockCurrentUser';
import { mockScaleSetting } from './mockScaleSetting';
import { mockWells } from './mockWells';

export const mockTestAssetId = 70321078;

export const mockAppProps = {
  onSettingChange: jest.fn(),
  setSecondaryMenuItems: jest.fn(),
  app: {
    id: -1,
    app: {
      app_key: 'corva.treatment_plot.ui',
      platform: 'dev_center',
    },
    settings: {
      package: '0.13.0',
      fracFleetId: 58595,
      padId: 85113,
      dataSetting: {
        selectedPress: ['wellhead_pressure'],
        selectedOffsetPressure: [],
        selectedRate: ['slurry_flow_rate_in'],
        selectedVolumeChemical: [],
        selectedMassChemical: [],
        selectedMassConcentrationProppant: ['total_proppant_concentration'],
        selectedMassProppant: [],
        selectedTotalVolume: [],
        selectedCustomChannels: [],
      },
      isRealtimeSidebarOpen: true,
      settingsByAsset: {
        'pad--85113': {
          mode: 'custom',
          selectedAssets: [520912],
        },
      },
    },
    package: {
      manifest: {
        format: 1,
        license: {
          type: 'MIT',
          url: 'https://www.oandgexample.com/license/',
        },
        developer: {
          authors: [],
        },
        application: {
          type: 'ui',
          key: 'corva.treatment_plot.ui',
          visibility: 'private',
          name: 'Treatment Plot',
          category: 'completionAsset',
          segments: ['completion'],
          ui: {
            initial_size: {
              w: 12,
              h: 16,
            },
          },
        },
        settings: {
          entrypoint: {
            file: 'src/index.js',
            function: 'handler',
          },
          environment: {},
          runtime: 'ui',
        },
        datasets: {},
      },
      build: 'corva.treatment_plot.ui-0.13.0',
      version: '0.13.0',
    },
  },
  package: '0.13.0',
  fracFleetId: 58595,
  padId: 85113,
  dataSetting: {
    selectedPress: ['wellhead_pressure'],
    selectedOffsetPressure: [],
    selectedRate: ['slurry_flow_rate_in'],
    selectedVolumeChemical: [],
    selectedMassChemical: [],
    selectedMassConcentrationProppant: ['total_proppant_concentration'],
    selectedMassProppant: [],
    selectedTotalVolume: [],
    selectedCustomChannels: [],
  },
  isRealtimeSidebarOpen: true,
  settingsByAsset: {
    'pad--85113': {
      mode: 'custom',
      selectedAssets: [520912],
    },
  },
  fracFleet: {
    type: 'frac_fleet',
    id: '58595',
    name: 'Wolfgang Fleet',
    current_pad_id: 85113,
    pad_frac_fleets: [
      {
        type: 'pad_frac_fleet',
        id: '20792',
        current: true,
        last_current_at: '2023-05-25T16:27:30.960Z',
        pad: {
          id: 85113,
          name: 'TimberPSD 2H/3H',
          created_at: '2023-05-25T16:26:17.589Z',
          updated_at: '2023-05-25T21:15:56.235Z',
          company_id: 15,
          program_id: 1585,
          lon_lat: {
            longitude: 33.333,
            latitude: 50,
          },
          drillout_unit_id: null,
          last_active_at: '2023-05-15T18:05:00.000Z',
        },
        frac_fleet: {
          id: 58595,
          name: 'Wolfgang Fleet',
          created_at: '2023-05-25T16:27:30.049Z',
          updated_at: '2023-05-25T21:15:56.225Z',
          company_id: 15,
          program_id: 1585,
          lon_lat: {
            longitude: 33.333,
            latitude: 50,
          },
          frac_fleet_vendor: null,
          last_active_at: '2023-05-15T18:05:00.000Z',
        },
      },
    ],
    relationshipNames: ['pad_frac_fleets'],
  },
  wells: mockWells,
  coordinates: {
    w: 12,
    h: 16,
    x: 0,
    y: 0,
    pixelHeight: 630,
    pixelWidth: 1400,
  },
  currentUser: mockCurrentUser,
  devCenterRouter: {
    location: {
      pathname: '/app',
      query: {},
    },
  },
  appHeaderProps: {
    app: {
      id: -1,
      app: {
        app_key: 'corva.treatment_plot.ui',
        platform: 'dev_center',
      },
      settings: {
        package: '0.13.0',
        fracFleetId: 58595,
        padId: 85113,
        dataSetting: {
          selectedPress: ['wellhead_pressure'],
          selectedOffsetPressure: [],
          selectedRate: ['slurry_flow_rate_in'],
          selectedVolumeChemical: [],
          selectedMassChemical: [],
          selectedMassConcentrationProppant: ['total_proppant_concentration'],
          selectedMassProppant: [],
          selectedTotalVolume: [],
          selectedCustomChannels: [],
        },
        isRealtimeSidebarOpen: true,
        settingsByAsset: {
          'pad--85113': {
            mode: 'custom',
            selectedAssets: [520912],
          },
        },
      },
      package: {
        manifest: {
          format: 1,
          license: {
            type: 'MIT',
            url: 'https://www.oandgexample.com/license/',
          },
          developer: {
            authors: [],
          },
          application: {
            type: 'ui',
            key: 'corva.treatment_plot.ui',
            visibility: 'private',
            name: 'Treatment Plot',
            category: 'completionAsset',
            segments: ['completion'],
            ui: {
              initial_size: {
                w: 12,
                h: 16,
              },
            },
          },
          settings: {
            entrypoint: {
              file: 'src/index.js',
              function: 'handler',
            },
            environment: {},
            runtime: 'ui',
          },
          datasets: {},
        },
        build: 'corva.treatment_plot.ui-0.13.0',
        version: '0.13.0',
      },
    },
    appLastAnnotation: null,
    appSettings: {
      package: '0.13.0',
      fracFleetId: 58595,
      padId: 85113,
      dataSetting: {
        selectedPress: ['wellhead_pressure'],
        selectedOffsetPressure: [],
        selectedRate: ['slurry_flow_rate_in'],
        selectedVolumeChemical: [],
        selectedMassChemical: [],
        selectedMassConcentrationProppant: ['total_proppant_concentration'],
        selectedMassProppant: [],
        selectedTotalVolume: [],
        selectedCustomChannels: [],
      },
      isRealtimeSidebarOpen: true,
      settingsByAsset: {
        'pad--85113': {
          mode: 'custom',
          selectedAssets: [520912],
        },
      },
    },
    coordinates: {
      w: 12,
      h: 16,
      x: 0,
      y: 0,
      pixelHeight: 630,
      pixelWidth: 1400,
    },
    currentUser: mockCurrentUser,
    isMaximized: false,
    layoutEnvironment: {
      type: 'general',
      pdfReportMode: false,
    },
    fracFleet: {
      type: 'frac_fleet',
      id: '58595',
      name: 'Wolfgang Fleet',
      current_pad_id: 85113,
      pad_frac_fleets: [
        {
          type: 'pad_frac_fleet',
          id: '20792',
          current: true,
          last_current_at: '2023-05-25T16:27:30.960Z',
          pad: {
            id: 85113,
            name: 'TimberPSD 2H/3H',
            created_at: '2023-05-25T16:26:17.589Z',
            updated_at: '2023-05-25T21:15:56.235Z',
            company_id: 15,
            program_id: 1585,
            lon_lat: {
              longitude: 33.333,
              latitude: 50,
            },
            drillout_unit_id: null,
            last_active_at: '2023-05-15T18:05:00.000Z',
          },
          frac_fleet: {
            id: 58595,
            name: 'Wolfgang Fleet',
            created_at: '2023-05-25T16:27:30.049Z',
            updated_at: '2023-05-25T21:15:56.225Z',
            company_id: 15,
            program_id: 1585,
            lon_lat: {
              longitude: 33.333,
              latitude: 50,
            },
            frac_fleet_vendor: null,
            last_active_at: '2023-05-15T18:05:00.000Z',
          },
        },
      ],
      relationshipNames: ['pad_frac_fleets'],
    },
    wells: mockWells,
  },
  isNative: false,
  layoutEnvironment: {
    type: 'general',
    pdfReportMode: false,
  },
  timestamp: null,
  appId: 1,
  theme: {},
  well: null,
  offsetSetting: {},
  filterSetting: {},
  customTimeSetting: {
    start: null,
    end: null,
  },
  scaleSetting: mockScaleSetting,
  activitySetting: [],
  graphColors: {
    wellhead_pressure: '#F50057',
    pipe_frictional_pressure_loss: '#D8496B',
    nwb_frictional_pressure_loss: '#807DFF',
    bottomhole_pressure: '#4DCFB3',
    net_pressure: '#EE752F',
    pumpside_pressure: '#855CF8',
    backside_pressure: '#32aa32',
    hydrostatic_pressure: '#E458C8',
    'offset_pressure_3mh-2_int': '#73AFAA',
    'offset_pressure_2smh-2_int': '#51A8BA',
    'offset_pressure_3mh-2_zipper': '#1C8195',
    'offset_pressure_2smh-2_zipper': '#006073',
    clean_flow_rate_in: '#7CC900',
    slurry_flow_rate_in: '#64B5FF',
    gel: '#84F4F7',
    acid: '#6ec732',
    friction_reducer: '#FFA891',
    friction_reducer_extra: '#91FFA8',
    total_friction_reducer: '#FF91A8',
    fluid_loss: '#c7bd32',
    cross_linker: '#B0CA87',
    enzyme_breaker: '#32b8c7',
    ploymer_plug: '#9fc732',
    acid_inhibitor: '#AB9081',
    acid_retarder: '#7CC6FE',
    emulsifier: '#5DFDCB',
    clay_stabilizer: '#9C6B20',
    surfactant: '#FFF689',
    non_emulsifier: '#C0DF85',
    fines_suspender: '#7B8E55',
    anti_sludge: '#07393C',
    scale_inhibitor: '#C0E5CA',
    iron_control: '#CD5334',
    oxygen_scavenger: '#DFF283',
    mutual_solvent: '#ad5ec7',
    corrosion_inhibitor: '#7C2209',
    paraffin_control: '#F5A65B',
    biocide: '#E9B76A',
    ph_adjusting_agent: '#519872',
    accelerator: '#5E3023',
    instant_crosslinker: '#6E6E23',
    delayed_crosslinker: '#7E306E',
    liquid_breaker: '#233023',
    divertor: '#BB9394',
    powder_breaker: '#c732b8',
    powder_gel: '#308E23',
    powder_friction_reducer: '#30239E',
    powder_enzyme_breaker: '#A32A78',
    total_proppant_concentration: '#FF8F0B',
    bottomhole_proppant_concentration: '#9F4BED',
    proppant_1_concentration: '#7EB93A',
    proppant_2_concentration: '#6785E8',
    total_proppant_mass: '#EE964B',
    proppant_1_mass: '#C6C013',
    proppant_2_mass: '#7ff577',
    total_clean_volume_in: '#257CFF',
    total_slurry_volume_in: '#7169AE',
  },
  offsetGraphColors: {},
  isAssetViewer: false,
  isFilterSidebarOpen: true,
  rtValuesSetting: [],
  sideSetting: {
    showRealtimeValues: true,
    showFeedBar: true,
    showLegendBar: true,
    showSlider: true,
    showStreamboxStatus: false,
  },
};

export const mockAppHeaderProps = {
  appHeaderProps: mockAppProps.appHeaderProps,
  onAppOffsetSettingChange: jest.fn(),
  onSettingChange: jest.fn(),
};
