/**
 * This is a real example of the props that'll come
 * to the App component. You'll need to manually update it
 * if in the future some new properties are added
 */

export const mockAppProps = {
  onSettingChange: jest.fn(),
  onSettingsChange: jest.fn(),
  setIsFullscreenModalMode: jest.fn(),
  setIsMaximized: jest.fn(),
  setMainMenuItems: jest.fn(),
  setSecondaryMenuItems: jest.fn(),
  isExampleCheckboxChecked: true,
  app: {
    id: -1,
    app: {
      app_key: 'corva.shell_hypercare.ui',
      platform: 'dev_center',
    },
    settings: {
      package: '0.0.1',
      fracFleetId: 59340,
      padId: null,
    },
    package: {
      manifest: {
        format: 1,
        license: {
          type: 'MIT',
          url: 'https://www.oandgexample.com/license/',
        },
        developer: {
          name: 'O&G Company',
          identifier: 'oandgc',
          authors: [],
        },
        application: {
          type: 'ui',
          key: 'corva.shell_hypercare.ui',
          visibility: 'private',
          name: 'Hypercare',
          description: 'This is the description of my app. You can do great things with it!',
          summary: 'More information about this app goes here',
          category: 'completionAnalytics',
          website: 'https://www.oandgexample.com/my-app/',
          segments: ['completion'],
          ui: {
            initial_size: {
              w: 4,
              h: 10,
            },
            multi_rig: false,
            full_screen_report: false,
          },
        },
        settings: {
          entrypoint: {
            file: 'src/index.js',
            function: 'handler',
          },
          environment: {},
          runtime: 'ui',
          app: {
            log_type: 'time',
          },
        },
        datasets: {},
      },
      build: 'corva.shell_hypercare.ui-0.0.1',
      version: '0.0.1',
    },
  },
  package: '0.0.1',
  fracFleetId: 59340,
  padId: null,
  fracFleet: {
    type: 'frac_fleet',
    id: '59340',
    name: 'HES - Chiefs - WCU 1',
    current_pad_id: 86175,
    pad_frac_fleets: [
      {
        type: 'pad_frac_fleet',
        id: '21168',
        current: true,
        last_current_at: '2023-06-07T09:04:27.696Z',
        pad: {
          id: 86175,
          name: 'ZebcoPSD 27-39 5WA/7JM/9LS - Server 1',
          created_at: '2023-06-07T08:51:55.805Z',
          updated_at: '2023-06-23T08:06:52.667Z',
          company_id: 15,
          program_id: 1585,
          lon_lat: {
            longitude: 32.10101,
            latitude: 49,
          },
          drillout_unit_id: null,
          last_active_at: '2023-06-23T08:06:50.000Z',
        },
        frac_fleet: {
          id: 59340,
          name: 'HES - Chiefs - WCU 1',
          created_at: '2023-06-07T09:04:27.267Z',
          updated_at: '2023-06-23T08:06:52.661Z',
          company_id: 15,
          program_id: 1585,
          lon_lat: {
            longitude: 32.10101,
            latitude: 49,
          },
          frac_fleet_vendor: null,
          last_active_at: '2023-06-23T08:06:50.000Z',
          billing_company_id: null,
        },
      },
    ],
    relationshipNames: ['pad_frac_fleets'],
  },
  coordinates: {
    x: 0,
    y: 0,
    w: 6,
    h: 15,
    pixelHeight: 590,
    pixelWidth: 652,
  },
  currentUser: {
    id: 6779,
    company_id: 1,
    first_name: 'Alexandr',
    last_name: 'Malasinschii',
    email: 'alexandr.malasinschii@corva.dev',
    mobile: '',
    created_at: '2021-11-15T14:56:43.882Z',
    terms_acceptance_at: '2021-11-15T15:12:36.367Z',
    profile_photo: null,
    recently_viewed_asset_ids: [66578716, 41762264, 71211778],
    unit_system: {
      yp: 'hsf',
      oil: 'bbl',
      area: 'ft2',
      mass: 'lb',
      time: 'min',
      angle: 'deg',
      force: 'klbf',
      power: 'hp',
      speed: 'ft/h',
      length: 'ft',
      torque: 'ft-klbf',
      volume: 'bbl',
      current: 'mA',
      density: 'lb/gal',
      voltage: 'mV',
      porosity: 'pu',
      pressure: 'psi',
      velocity: 'ft/h',
      gasVolume: 'Mscf',
      msePressure: 'ksi',
      oilFlowRate: 'bbl/min',
      resistivity: 'ohmm',
      shortLength: 'in',
      temperature: 'F',
      massFlowRate: 'lb/min',
      permiability: 'md',
      concentration: 'ppm',
      fluidVelocity: 'ft/min',
      massPerLength: 'lb-ft',
      anglePerLength: 'dp100f',
      lengthPerAngle: 'in/rev',
      volumeFlowRate: 'gal/min',
      angularVelocity: 'rpm',
      inversePressure: 'i-psi',
      acousticSlowness: 'us/ft',
      formationDensity: 'g/m3',
      gasConcentration: 'Units (0-5000u)',
      pressureGradient: 'psi/ft',
      massConcentration: 'lb/gal',
      revolutionPerVolume: 'rpg',
      spontaneousPotential: 'mV',
      chemMassConcentration: 'lb/Mgal',
      chemVolumeConcentration: 'gal/Mgal',
    },
    role: 'developeradmin',
    title: null,
    group: null,
    favorite_asset_id: null,
    current_segment: 'drilling',
    theme: 'dark',
    messaging_id: 'qa_6779',
    restricted_assets: [],
    restricted_programs: [],
    settings: {
      favorites: {
        rigs: ['1184', '87837'],
      },
      restrict_by: 'rig',
      feed_filters: {
        company_id: null,
        start_date: '06/19/23 18:44',
        content_types: [
          'post',
          'completion_operational_note',
          'fluid_report',
          'completion_npt_event',
          'traces_memo',
          'completion_operation_summary',
          'app_annotation',
          'npt_event',
          'operation_summary',
          'survey_station',
          'completion_actual_stage',
          'driller_memo',
          'daily_cost',
          'completion_daily_cost',
          'bha',
          'document',
          'alert',
          'completion_document',
          'operational_note',
          'lessons_learned',
        ],
        selected_rigs_ids: [],
        selected_user_ids: [],
        users_radio_value: 'all',
        assets_radio_value: 'all',
        date_range_radio_value: 'last24hours',
      },
      sms_blacklisted: false,
      favorit_asset_ids: [31621, 40345755],
      restricted_assets: [],
      alerts_list_filters: {
        end_date: '12/31/22 00:00',
        segments: ['drilling', 'completion'],
        alert_name: '',
        start_date: '01/01/22 00:00',
        validation: 'all',
        alert_levels: ['info', 'warning', 'critical'],
        subscription: '',
        classification: 'all',
        selected_rigs_id: '74311907',
        selected_rigs_ids: [],
        assets_radio_value: 'all',
        date_range_radio_value: 'custom',
      },
      restricted_programs: [],
      last_new_alerts_check: '2023-06-14T13:37:46.065Z',
      notifications_filters: {
        content_types: ['asset'],
      },
      last_new_feed_items_check: '2023-06-20T09:44:28.648Z',
      participates_in_beta_apps: false,
      formation_evaluation_custom_gradients: [
        {
          id: 'test',
          name: 'test',
          gradientStops: [
            {
              pos: 0,
              color: '#ffe300',
            },
            {
              pos: 31.84357541899441,
              color: 'red',
            },
            {
              pos: 59.49720670391061,
              color: '#408e00',
            },
            {
              pos: 86.87150837988827,
              color: '#714cff',
            },
            {
              pos: 100,
              color: '#1edcc1',
            },
          ],
        },
      ],
    },
    last_sign_in_at: '2023-07-21T01:29:38.033Z',
    locked_access: false,
    unit_ids: [],
    intercom_admin_id: null,
    resource: [],
    intercom_user_hash: 'decf043b810b5daaaf82f8577552f1aac695cd7eff71906b7869d59a1dffc353',
    profile_groups: [],
    preference: {
      id: 6765,
      user: {
        id: 6779,
        company_id: 1,
        first_name: 'Alexandr',
        last_name: 'Malasinschii',
        email: 'alexandr.malasinschii@corva.dev',
        role: 'developeradmin',
        created_at: '2021-11-15T14:56:43.882Z',
        updated_at: '2023-08-17T02:36:59.742Z',
        recently_viewed_asset_ids: [66578716, 41762264, 71211778],
        unit_system: {
          yp: 'hsf',
          oil: 'bbl',
          area: 'ft2',
          mass: 'lb',
          time: 'min',
          angle: 'deg',
          force: 'klbf',
          power: 'hp',
          speed: 'ft/h',
          length: 'ft',
          torque: 'ft-klbf',
          volume: 'bbl',
          current: 'mA',
          density: 'lb/gal',
          voltage: 'mV',
          porosity: 'pu',
          pressure: 'psi',
          velocity: 'ft/h',
          gasVolume: 'Mscf',
          msePressure: 'ksi',
          oilFlowRate: 'bbl/min',
          resistivity: 'ohmm',
          shortLength: 'in',
          temperature: 'F',
          massFlowRate: 'lb/min',
          permiability: 'md',
          concentration: 'ppm',
          fluidVelocity: 'ft/min',
          massPerLength: 'lb-ft',
          anglePerLength: 'dp100f',
          lengthPerAngle: 'in/rev',
          volumeFlowRate: 'gal/min',
          angularVelocity: 'rpm',
          inversePressure: 'i-psi',
          acousticSlowness: 'us/ft',
          formationDensity: 'g/m3',
          gasConcentration: 'Units (0-5000u)',
          pressureGradient: 'psi/ft',
          massConcentration: 'lb/gal',
          revolutionPerVolume: 'rpg',
          spontaneousPotential: 'mV',
          chemMassConcentration: 'lb/Mgal',
          chemVolumeConcentration: 'gal/Mgal',
        },
        mobile: '',
        terms_acceptance_at: '2021-11-15T15:12:36.367Z',
        messaging_id: 'qa_6779',
        settings: {
          favorites: {
            rigs: ['1184', '87837'],
          },
          restrict_by: 'rig',
          feed_filters: {
            company_id: null,
            start_date: '06/19/23 18:44',
            content_types: [
              'post',
              'completion_operational_note',
              'fluid_report',
              'completion_npt_event',
              'traces_memo',
              'completion_operation_summary',
              'app_annotation',
              'npt_event',
              'operation_summary',
              'survey_station',
              'completion_actual_stage',
              'driller_memo',
              'daily_cost',
              'completion_daily_cost',
              'bha',
              'document',
              'alert',
              'completion_document',
              'operational_note',
              'lessons_learned',
            ],
            selected_rigs_ids: [],
            selected_user_ids: [],
            users_radio_value: 'all',
            assets_radio_value: 'all',
            date_range_radio_value: 'last24hours',
          },
          sms_blacklisted: false,
          favorit_asset_ids: [31621, 40345755],
          restricted_assets: [],
          alerts_list_filters: {
            end_date: '12/31/22 00:00',
            segments: ['drilling', 'completion'],
            alert_name: '',
            start_date: '01/01/22 00:00',
            validation: 'all',
            alert_levels: ['info', 'warning', 'critical'],
            subscription: '',
            classification: 'all',
            selected_rigs_id: '74311907',
            selected_rigs_ids: [],
            assets_radio_value: 'all',
            date_range_radio_value: 'custom',
          },
          restricted_programs: [],
          last_new_alerts_check: '2023-06-14T13:37:46.065Z',
          notifications_filters: {
            content_types: ['asset'],
          },
          last_new_feed_items_check: '2023-06-20T09:44:28.648Z',
          participates_in_beta_apps: false,
          formation_evaluation_custom_gradients: [
            {
              id: 'test',
              name: 'test',
              gradientStops: [
                {
                  pos: 0,
                  color: '#ffe300',
                },
                {
                  pos: 31.84357541899441,
                  color: 'red',
                },
                {
                  pos: 59.49720670391061,
                  color: '#408e00',
                },
                {
                  pos: 86.87150837988827,
                  color: '#714cff',
                },
                {
                  pos: 100,
                  color: '#1edcc1',
                },
              ],
            },
          ],
        },
        theme: 'dark',
        title: null,
        profile_photo: null,
        favorite_asset_id: null,
        current_segment: 'drilling',
        state: 'active',
        created_by: 5657,
        provisioner: 'internal',
        intercom_admin_id: null,
        resource: [],
        group: null,
      },
      push_notifications_enabled: true,
      emails_enabled: true,
      sms_enabled: true,
      alert_levels: ['info', 'warning', 'critical'],
      play_alerts_sound: true,
      show_intercom_icon: true,
      segment: ['drilling', 'completion'],
      disable_create_dashboard: false,
      disable_costs: false,
      disable_documents: false,
      realtime_operation_mode: false,
      disable_file_upload: false,
      stay_on_app_store: false,
    },
    company: {
      id: 1,
      name: 'Corva',
      time_zone: 'America/Chicago',
      language: 'en',
      provider: 'corva',
      unit_system: {
        yp: 'hsf',
        oil: 'bbl',
        area: 'ft2',
        mass: 'lb',
        time: 'min',
        angle: 'deg',
        force: 'klbf',
        power: 'hp',
        speed: 'ft/h',
        length: 'ft',
        system: 'imperial',
        torque: 'ft-klbf',
        volume: 'gal',
        current: 'mA',
        density: 'ppg',
        voltage: 'mV',
        pressure: 'psi',
        velocity: 'ft/h',
        msePressure: 'ksi',
        oilFlowRate: 'bbl/min',
        shortLength: 'in',
        temperature: 'F',
        massFlowRate: 'lb/min',
        fluidVelocity: 'ft/min',
        massPerLength: 'lb-ft',
        anglePerLength: 'dp100f',
        lengthPerAngle: 'in/rev',
        volumeFlowRate: 'gal/min',
        inversePressure: 'i-psi',
        pressureGradient: 'psi/ft',
        massConcentration: 'lb/gal',
        revolutionPerVolume: 'rpg',
        chemMassConcentration: 'lb/Mgal',
        chemVolumeConcentration: 'gal/Mgal',
      },
      dev_center_enabled: true,
      workflows_enabled: true,
      with_subscription: true,
      competitor_analysis_enabled: true,
    },
    groups: [
      {
        id: 549,
        name: 'developeradmin',
        company_id: 1,
      },
      {
        id: 553,
        name: 'corvaadmin',
        company_id: 1,
      },
    ],
  },
  devCenterRouter: {
    location: {
      pathname: '/app',
      query: {},
    },
  },
  appHeaderProps: {
    app: {
      id: -1,
      app: {
        app_key: 'corva.shell_hypercare.ui',
        platform: 'dev_center',
      },
      settings: {
        package: '0.0.1',
        fracFleetId: 59340,
        padId: null,
      },
      package: {
        manifest: {
          format: 1,
          license: {
            type: 'MIT',
            url: 'https://www.oandgexample.com/license/',
          },
          developer: {
            name: 'O&G Company',
            identifier: 'oandgc',
            authors: [],
          },
          application: {
            type: 'ui',
            key: 'corva.shell_hypercare.ui',
            visibility: 'private',
            name: 'Hypercare',
            description: 'This is the description of my app. You can do great things with it!',
            summary: 'More information about this app goes here',
            category: 'completionAnalytics',
            website: 'https://www.oandgexample.com/my-app/',
            segments: ['completion'],
            ui: {
              initial_size: {
                w: 4,
                h: 10,
              },
              multi_rig: false,
              full_screen_report: false,
            },
          },
          settings: {
            entrypoint: {
              file: 'src/index.js',
              function: 'handler',
            },
            environment: {},
            runtime: 'ui',
            app: {
              log_type: 'time',
            },
          },
          datasets: {},
        },
        build: 'corva.shell_hypercare.ui-0.0.1',
        version: '0.0.1',
      },
    },
    appLastAnnotation: null,
    appSettings: {
      package: '0.0.1',
      fracFleetId: 59340,
      padId: null,
    },
    coordinates: {
      x: 0,
      y: 0,
      w: 6,
      h: 15,
      pixelHeight: 590,
      pixelWidth: 652,
    },
    currentUser: {
      id: 6779,
      company_id: 1,
      first_name: 'Alexandr',
      last_name: 'Malasinschii',
      email: 'alexandr.malasinschii@corva.dev',
      mobile: '',
      created_at: '2021-11-15T14:56:43.882Z',
      terms_acceptance_at: '2021-11-15T15:12:36.367Z',
      profile_photo: null,
      recently_viewed_asset_ids: [66578716, 41762264, 71211778],
      unit_system: {
        yp: 'hsf',
        oil: 'bbl',
        area: 'ft2',
        mass: 'lb',
        time: 'min',
        angle: 'deg',
        force: 'klbf',
        power: 'hp',
        speed: 'ft/h',
        length: 'ft',
        torque: 'ft-klbf',
        volume: 'bbl',
        current: 'mA',
        density: 'lb/gal',
        voltage: 'mV',
        porosity: 'pu',
        pressure: 'psi',
        velocity: 'ft/h',
        gasVolume: 'Mscf',
        msePressure: 'ksi',
        oilFlowRate: 'bbl/min',
        resistivity: 'ohmm',
        shortLength: 'in',
        temperature: 'F',
        massFlowRate: 'lb/min',
        permiability: 'md',
        concentration: 'ppm',
        fluidVelocity: 'ft/min',
        massPerLength: 'lb-ft',
        anglePerLength: 'dp100f',
        lengthPerAngle: 'in/rev',
        volumeFlowRate: 'gal/min',
        angularVelocity: 'rpm',
        inversePressure: 'i-psi',
        acousticSlowness: 'us/ft',
        formationDensity: 'g/m3',
        gasConcentration: 'Units (0-5000u)',
        pressureGradient: 'psi/ft',
        massConcentration: 'lb/gal',
        revolutionPerVolume: 'rpg',
        spontaneousPotential: 'mV',
        chemMassConcentration: 'lb/Mgal',
        chemVolumeConcentration: 'gal/Mgal',
      },
      role: 'developeradmin',
      title: null,
      group: null,
      favorite_asset_id: null,
      current_segment: 'drilling',
      theme: 'dark',
      messaging_id: 'qa_6779',
      restricted_assets: [],
      restricted_programs: [],
      settings: {
        favorites: {
          rigs: ['1184', '87837'],
        },
        restrict_by: 'rig',
        feed_filters: {
          company_id: null,
          start_date: '06/19/23 18:44',
          content_types: [
            'post',
            'completion_operational_note',
            'fluid_report',
            'completion_npt_event',
            'traces_memo',
            'completion_operation_summary',
            'app_annotation',
            'npt_event',
            'operation_summary',
            'survey_station',
            'completion_actual_stage',
            'driller_memo',
            'daily_cost',
            'completion_daily_cost',
            'bha',
            'document',
            'alert',
            'completion_document',
            'operational_note',
            'lessons_learned',
          ],
          selected_rigs_ids: [],
          selected_user_ids: [],
          users_radio_value: 'all',
          assets_radio_value: 'all',
          date_range_radio_value: 'last24hours',
        },
        sms_blacklisted: false,
        favorit_asset_ids: [31621, 40345755],
        restricted_assets: [],
        alerts_list_filters: {
          end_date: '12/31/22 00:00',
          segments: ['drilling', 'completion'],
          alert_name: '',
          start_date: '01/01/22 00:00',
          validation: 'all',
          alert_levels: ['info', 'warning', 'critical'],
          subscription: '',
          classification: 'all',
          selected_rigs_id: '74311907',
          selected_rigs_ids: [],
          assets_radio_value: 'all',
          date_range_radio_value: 'custom',
        },
        restricted_programs: [],
        last_new_alerts_check: '2023-06-14T13:37:46.065Z',
        notifications_filters: {
          content_types: ['asset'],
        },
        last_new_feed_items_check: '2023-06-20T09:44:28.648Z',
        participates_in_beta_apps: false,
        formation_evaluation_custom_gradients: [
          {
            id: 'test',
            name: 'test',
            gradientStops: [
              {
                pos: 0,
                color: '#ffe300',
              },
              {
                pos: 31.84357541899441,
                color: 'red',
              },
              {
                pos: 59.49720670391061,
                color: '#408e00',
              },
              {
                pos: 86.87150837988827,
                color: '#714cff',
              },
              {
                pos: 100,
                color: '#1edcc1',
              },
            ],
          },
        ],
      },
      last_sign_in_at: '2023-07-21T01:29:38.033Z',
      locked_access: false,
      unit_ids: [],
      intercom_admin_id: null,
      resource: [],
      intercom_user_hash: 'decf043b810b5daaaf82f8577552f1aac695cd7eff71906b7869d59a1dffc353',
      profile_groups: [],
      preference: {
        id: 6765,
        user: {
          id: 6779,
          company_id: 1,
          first_name: 'Alexandr',
          last_name: 'Malasinschii',
          email: 'alexandr.malasinschii@corva.dev',
          role: 'developeradmin',
          created_at: '2021-11-15T14:56:43.882Z',
          updated_at: '2023-08-17T02:36:59.742Z',
          recently_viewed_asset_ids: [66578716, 41762264, 71211778],
          unit_system: {
            yp: 'hsf',
            oil: 'bbl',
            area: 'ft2',
            mass: 'lb',
            time: 'min',
            angle: 'deg',
            force: 'klbf',
            power: 'hp',
            speed: 'ft/h',
            length: 'ft',
            torque: 'ft-klbf',
            volume: 'bbl',
            current: 'mA',
            density: 'lb/gal',
            voltage: 'mV',
            porosity: 'pu',
            pressure: 'psi',
            velocity: 'ft/h',
            gasVolume: 'Mscf',
            msePressure: 'ksi',
            oilFlowRate: 'bbl/min',
            resistivity: 'ohmm',
            shortLength: 'in',
            temperature: 'F',
            massFlowRate: 'lb/min',
            permiability: 'md',
            concentration: 'ppm',
            fluidVelocity: 'ft/min',
            massPerLength: 'lb-ft',
            anglePerLength: 'dp100f',
            lengthPerAngle: 'in/rev',
            volumeFlowRate: 'gal/min',
            angularVelocity: 'rpm',
            inversePressure: 'i-psi',
            acousticSlowness: 'us/ft',
            formationDensity: 'g/m3',
            gasConcentration: 'Units (0-5000u)',
            pressureGradient: 'psi/ft',
            massConcentration: 'lb/gal',
            revolutionPerVolume: 'rpg',
            spontaneousPotential: 'mV',
            chemMassConcentration: 'lb/Mgal',
            chemVolumeConcentration: 'gal/Mgal',
          },
          mobile: '',
          terms_acceptance_at: '2021-11-15T15:12:36.367Z',
          messaging_id: 'qa_6779',
          settings: {
            favorites: {
              rigs: ['1184', '87837'],
            },
            restrict_by: 'rig',
            feed_filters: {
              company_id: null,
              start_date: '06/19/23 18:44',
              content_types: [
                'post',
                'completion_operational_note',
                'fluid_report',
                'completion_npt_event',
                'traces_memo',
                'completion_operation_summary',
                'app_annotation',
                'npt_event',
                'operation_summary',
                'survey_station',
                'completion_actual_stage',
                'driller_memo',
                'daily_cost',
                'completion_daily_cost',
                'bha',
                'document',
                'alert',
                'completion_document',
                'operational_note',
                'lessons_learned',
              ],
              selected_rigs_ids: [],
              selected_user_ids: [],
              users_radio_value: 'all',
              assets_radio_value: 'all',
              date_range_radio_value: 'last24hours',
            },
            sms_blacklisted: false,
            favorit_asset_ids: [31621, 40345755],
            restricted_assets: [],
            alerts_list_filters: {
              end_date: '12/31/22 00:00',
              segments: ['drilling', 'completion'],
              alert_name: '',
              start_date: '01/01/22 00:00',
              validation: 'all',
              alert_levels: ['info', 'warning', 'critical'],
              subscription: '',
              classification: 'all',
              selected_rigs_id: '74311907',
              selected_rigs_ids: [],
              assets_radio_value: 'all',
              date_range_radio_value: 'custom',
            },
            restricted_programs: [],
            last_new_alerts_check: '2023-06-14T13:37:46.065Z',
            notifications_filters: {
              content_types: ['asset'],
            },
            last_new_feed_items_check: '2023-06-20T09:44:28.648Z',
            participates_in_beta_apps: false,
            formation_evaluation_custom_gradients: [
              {
                id: 'test',
                name: 'test',
                gradientStops: [
                  {
                    pos: 0,
                    color: '#ffe300',
                  },
                  {
                    pos: 31.84357541899441,
                    color: 'red',
                  },
                  {
                    pos: 59.49720670391061,
                    color: '#408e00',
                  },
                  {
                    pos: 86.87150837988827,
                    color: '#714cff',
                  },
                  {
                    pos: 100,
                    color: '#1edcc1',
                  },
                ],
              },
            ],
          },
          theme: 'dark',
          title: null,
          profile_photo: null,
          favorite_asset_id: null,
          current_segment: 'drilling',
          state: 'active',
          created_by: 5657,
          provisioner: 'internal',
          intercom_admin_id: null,
          resource: [],
          group: null,
        },
        push_notifications_enabled: true,
        emails_enabled: true,
        sms_enabled: true,
        alert_levels: ['info', 'warning', 'critical'],
        play_alerts_sound: true,
        show_intercom_icon: true,
        segment: ['drilling', 'completion'],
        disable_create_dashboard: false,
        disable_costs: false,
        disable_documents: false,
        realtime_operation_mode: false,
        disable_file_upload: false,
        stay_on_app_store: false,
      },
      company: {
        id: 1,
        name: 'Corva',
        time_zone: 'America/Chicago',
        language: 'en',
        provider: 'corva',
        unit_system: {
          yp: 'hsf',
          oil: 'bbl',
          area: 'ft2',
          mass: 'lb',
          time: 'min',
          angle: 'deg',
          force: 'klbf',
          power: 'hp',
          speed: 'ft/h',
          length: 'ft',
          system: 'imperial',
          torque: 'ft-klbf',
          volume: 'gal',
          current: 'mA',
          density: 'ppg',
          voltage: 'mV',
          pressure: 'psi',
          velocity: 'ft/h',
          msePressure: 'ksi',
          oilFlowRate: 'bbl/min',
          shortLength: 'in',
          temperature: 'F',
          massFlowRate: 'lb/min',
          fluidVelocity: 'ft/min',
          massPerLength: 'lb-ft',
          anglePerLength: 'dp100f',
          lengthPerAngle: 'in/rev',
          volumeFlowRate: 'gal/min',
          inversePressure: 'i-psi',
          pressureGradient: 'psi/ft',
          massConcentration: 'lb/gal',
          revolutionPerVolume: 'rpg',
          chemMassConcentration: 'lb/Mgal',
          chemVolumeConcentration: 'gal/Mgal',
        },
        dev_center_enabled: true,
        workflows_enabled: true,
        with_subscription: true,
        competitor_analysis_enabled: true,
      },
      groups: [
        {
          id: 549,
          name: 'developeradmin',
          company_id: 1,
        },
        {
          id: 553,
          name: 'corvaadmin',
          company_id: 1,
        },
      ],
    },
    isMaximized: false,
    layoutEnvironment: {
      type: 'general',
      pdfReportMode: false,
    },
    fracFleet: {
      type: 'frac_fleet',
      id: '59340',
      name: 'HES - Chiefs - WCU 1',
      current_pad_id: 86175,
      pad_frac_fleets: [
        {
          type: 'pad_frac_fleet',
          id: '21168',
          current: true,
          last_current_at: '2023-06-07T09:04:27.696Z',
          pad: {
            id: 86175,
            name: 'ZebcoPSD 27-39 5WA/7JM/9LS - Server 1',
            created_at: '2023-06-07T08:51:55.805Z',
            updated_at: '2023-06-23T08:06:52.667Z',
            company_id: 15,
            program_id: 1585,
            lon_lat: {
              longitude: 32.10101,
              latitude: 49,
            },
            drillout_unit_id: null,
            last_active_at: '2023-06-23T08:06:50.000Z',
          },
          frac_fleet: {
            id: 59340,
            name: 'HES - Chiefs - WCU 1',
            created_at: '2023-06-07T09:04:27.267Z',
            updated_at: '2023-06-23T08:06:52.661Z',
            company_id: 15,
            program_id: 1585,
            lon_lat: {
              longitude: 32.10101,
              latitude: 49,
            },
            frac_fleet_vendor: null,
            last_active_at: '2023-06-23T08:06:50.000Z',
            billing_company_id: null,
          },
        },
      ],
      relationshipNames: ['pad_frac_fleets'],
    },
  },
  isNative: false,
  layoutEnvironment: {
    type: 'general',
    pdfReportMode: false,
  },
  timestamp: null,
  well: null,
};
